### ISSUE TITLE
Error on ViessmannOauthClient::getCode()

### ISSUE THREAD

**Issue by drlaplace** [thetrueavatar/Viessmann-Api#1]
I get following errors when I start Main.php. Before I insert user and pwd in credentials.

```
PHP Notice:  Undefined offset: 0 in /home/ss/Downloads/Viessmann-Api-master/src/Oauth/ViessmannOauthClient.php on line 78
PHP Fatal error:  Uncaught TypeError: Return value of Viessmann\Oauth\ViessmannOauthClient::getCode() must be of the type string, null returned in /home/ss/Downloads/Viessmann-Api-master/src/Oauth/ViessmannOauthClient.php:78

```

**Comment by thetrueavatar** [comment]
C'est parce que tu as un retourn à la ligne en trop dans ton fichier
credentials.properties.
Assure toi bien de n'avoir que 2 lignes dans ton fichier et donc pas de
ligne en dessous du password.
Bien à toi,

**Comment by thetrueavatar** [comment]
Sorry didn't notice you did write in english.
So be carreful to avoid having a carriage return after the second line
containing the password in the credentials.properties file.
Best Regards,

**Comment by drlaplace** [comment]
Thanks for your fast answer!
Unfortunately I have no carriage return after the second line. Error still the same.

**Comment by thetrueavatar** [comment]
Tu peux "hardcoder les user/mdp" directement dans le main si jamais. Je
suis passé par un fichier externe pour éviter de commiter par erreur mes
credentials sur le github.
Donc dans le Main.php tu mets:
$params=[
"user"=>"tonUser",
"pwd"=>"tonPassword",
"uri"=>"vicare://oauth-callback/everest"
];

**Comment by drlaplace** [comment]
Ok this worked! Great. But now I get the error:
`PHP Fatal error:  Uncaught OAuth\Common\Http\Exception\TokenResponseException: file_get_contents(https://iam.viessmann.com/idp/v1/token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /home/ss/Downloads/Viessmann-Api-master/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php:73
`

**Comment by drlaplace** [comment]
Sorry my bad. I get this Error code: 
`Fatal error:  Uncaught Error: Class 'TomPHP\Siren\Entity' not found in /home/ss/Downloads/Viessmann-Api-master/src/API/ViessmannAPI.php:58
`
Do I have to install anything?

**Comment by thetrueavatar** [comment]
Normalement non les librairies que j'utilises sont censées se trouver dans
vendor/lib.
J'utilise composer pour gérer les dépendances. Ce dernier génère un fichier
autoload.php à inclure dans son code afin de charger toutes les dépendances.
Normalement c'est fait dans le main via
require __DIR__ . '/../vendor/autoload.php';

**Comment by thetrueavatar** [comment]
Dans la class ViessmannApi je défini
use TomPHP\Siren\{ActionBuilder, Entity, Action};
C'est censé importer la class Entity qui est visiblement celle qu'il ne
trouve pas.
Pourriez-vous m'envoyer votre Main.php(sans les user/pwd bien sûr) ?

**Comment by thetrueavatar** [comment]
En fait, j'ai les mêmes problèmes que vous en lançant en command line. Je
lançais toujours via mon ide.
Je vais regarder.
Bien à vous,

**Comment by thetrueavatar** [comment]
Hum. Apparemment en ligne de commande l'autoload ne fonctionnerait qu'en
"interactive shell"(php -a). Je vais creuser pour voir comment mon ide fait.

**Comment by drlaplace** [comment]
OK. take your time. I can only test it again on Monday

**Comment by thetrueavatar** [comment]
tkt l'avantage c'est que j'ai le même prob donc je peux le fixer tout seul
;-).

**Comment by thetrueavatar** [comment]
Bon en fait, en effet, les librairies siren ne sont pas dans le github pour
une raison que j'ignore.
Je vais les rajouter...

**Comment by thetrueavatar** [comment]
Voila c'est réparé. J'avais mis une dépendance sur le master de Siren et
donc il voulait pas commiter. J'ai mis une dépendance sur la release 0.1 et
c'est en ordre now. J'ai fait moi même le test. Pas encore résolu le
problème du fichier de configuration mais si tu hardcodes le user/pwd ça
devrait marcher.

**Comment by thetrueavatar** [comment]
J'ai corrigé le problème de chargement depuis le fichiers. Tout devrait
être en ordre.

**Comment by drlaplace** [comment]
Thanks. It works!!
Is there any  to get the gas consumption? The given URL can't be found: 
heating.gas.consumption.dhw

**Comment by thetrueavatar** [comment]
Ben c'est un peu le problème que je recontre. Certaines données accessibles
avant ne le sont plus. Perso je n'arrive même plus à récupérer la
température courante de mon eau chaude sanitaire. Je vois que ViCare non
plus et pour cause elle n'est pas dans les données renvoyée par le nouveau
service.
Par contre, l'application VitrolPlus a la donnée mais elle attaque un tout
vieux service en SOAP et qui devrait prochainement être décommisionné...
j'ai déjà contacté le support Viessmann et il semble que la maj de fin Août
a été faite par erreur. Du coup l'application ViCare n'était pas prête et
c'est pour ça qu'on a accès à que dalle dedans. Le gars m'a dit que ça
serait ok dans la version 2.0.5. Pour le problème de données manquante, il
devait transmettre en Allemagne car c'es eux qui gère le backend exposant
les données....

Le lun. 10 sept. 2018 à 11:28, drlaplace <notifications@github.com> a
écrit :

**Comment by thetrueavatar** [comment]
Pour info, j'ai un peu adapté la façon de fonctionner. Je souhaitais que
mon api soit une librairie externe et j'ai réussi. Je compresse cela en
phar.
Désormais dans le répertoire bin il y a un bin/Viessmann-Api-0.1.phar
Dans le fichier d'appel, il suffit d'inclure
include 'phar://../bin/Viessmann-Api-0.1.phar/index.php';
J'ai mis le Main.php dans le répertoire example.
Comme cela, tu n'auras besoin que du fichier phar sur le raspberry en plus
du script Main.php.
Bien à toi,
Claude

**Comment by thetrueavatar** [comment]
Problème fixé
