### ISSUE TITLE
Gas Consumption

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#10]
Hi Claude,
I have seen that with NotTestTestMethod.php you started to get the gas consumption ...
Are still going on with this development and what would be the schedule for it.
Thanks Georg

**Comment by thetrueavatar** [comment]
I have developped this method but since I don't have the feature on my old
viessmann heating, I can't test it on the real server.
Some people have test it and told me it was working so the code is working.
However, you'll have to multiply data by 8 to match data displayed on the
real heating device. Moreover, it seems there is a bug when data >256kwh...
Guess we'll have to waite ViCare to display this that to be sure that
viessmann has finished ton work on it...
Best Regards,
Claude

**Comment by JungeG** [comment]
Hi Claude,
my Viessmann Heating has the feature, when I call the NotTestTestMethode.php I get:

> ./NotTestTestMethod.php
PHP Notice:  Array to string conversion in /etc/openhab2/scripts/viessmann/NotTestTestMethod.php on line 4

Line 4:
#!/usr/bin/php
<?php
include __DIR__ . '/bootstrap.php';
echo $viessmannApi->getDhwGasConsumption("day");
#echo $viessmannApi->getDhwGasConsumption("month");

Moreover, you said that I need the line 8 times ... how do I have to change the coding.

As mentioned I am not a php techi.
Thanks for support
Georg

**Comment by thetrueavatar** [comment]
in php to display an array you have to use
print_r($viessmannApi->getDhwGasConsumption("month"));
instead of echo. You'll have an array of value but each value must by 8.
Best Regards,

**Comment by JungeG** [comment]
Thanks Claude,
I did some testing and get values back:

> Dhw Day-Array
(
    [0] => 472
    [1] => 904
    [2] => 696
    [3] => 752
    [4] => 768
    [5] => 976
    [6] => 1016
)
Heating Day-Array
(
    [0] => 472
    [1] => 904
    [2] => 696
    [3] => 752
    [4] => 768
    [5] => 976
    [6] => 1016

But they are identical for Dhw and Heating.
Here my code:

> #!/usr/bin/php
<?php
include __DIR__ . '/bootstrap.php';
echo "Dhw Day-";
print_r($viessmannApi->getDhwGasConsumption("day"));
echo "Heating Day-";
print_r($viessmannApi->getHeatingGasConsumption("day"));

any idea what needs to be changed?
Thanks Georg

**Comment by thetrueavatar** [comment]
I know, it has already been told to me but can't fix it since it's
viessmann server which return the same data for both services...

**Comment by JungeG** [comment]
And what is the dimension of that value - I have checked and today's consumption should be 65 kWh. How can we compare this?

**Comment by thetrueavatar** [comment]
Those are the daily consumption for each days of the current week.
month would be the monthly consumption for the last 12 month
year would be the yearly consumption for the last 2 years
I has been told to me that data should be multiply by 8 to get kwh
equivalent but can't be sure until ViCare display itself the information.

**Comment by thetrueavatar** [comment]
According to some people data is not correctly send from viessmann server.
