### ISSUE TITLE
Error Message: ActivateEcoProgram.php

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#12]
Hi Claude,
I am testing again and want to activate the EcoMode. My code looks like: 

`#!/usr/bin/php
<?php
include __DIR__.'/bootstrap.php';
$viessmannApi->activateEcoProgram("18");`

When executing the code I get following error message:

> ./ActivateEcoProgram.php
PHP Fatal error:  Uncaught Viessmann\API\ViessmannApiException: Unable to set data for featureheating.circuits.0.operating.programs.ecoand action activate and data{"temperature":"18"}
 Reason: DEVICE_COMMUNICATION_ERROR in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php:769
Stack trace:
#0 phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(194): Viessmann\API\ViessmannAPI->setRawJsonData('heating.circuit...', 'activate', '{"temperature":...')
#1 /etc/openhab2/scripts/viessmann/ActivateEcoProgram.php(4): Viessmann\API\ViessmannAPI->activateEcoProgram('18')
#2 {main}
  thrown in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php on line 769

Since I have 2 heating circuits (0 and 1) - what is the right syntax for the call?
Thanks for your advice
Georg

**Comment by JungeG** [comment]
This wired formatted: here again
I am testing again and want to activate the EcoMode. My code looks like:

`#!/usr/bin/php >?php
  include __DIR__.'/bootstrap.php';
  $viessmannApi->activateEcoProgram("18");`

When executing the code I get following error message:

./ActivateEcoProgram.php
PHP Fatal error:  Uncaught Viessmann\API\ViessmannApiException: Unable to set data for featureheating.circuits.0.operating.programs.ecoand action activate and data{"temperature":"18"}
 Reason: DEVICE_COMMUNICATION_ERROR in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php:769
Stack trace:
#0 phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(194): Viessmann\API\ViessmannAPI->setRawJsonData('heating.circuit...', 'activate', '{"temperature":...')
#1 /etc/openhab2/scripts/viessmann/ActivateEcoProgram.php(4): Viessmann\API\ViessmannAPI->activateEcoProgram('18')
#2 {main}
  thrown in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php on line 769

Since I have 2 heating circuits (0 and 1) - what is the right syntax for the call? 
Thanks for your advice 
Georg

**Comment by thetrueavatar** [comment]
"DEVICE_COMMUNICATION_ERROR". As already explained, this is a viessmann
server error. Nothing to do but wait they fix it...

**Comment by JungeG** [comment]
Sorry Claude,
don't think so - because I can call other methods without any problems. Only the ActivateEcoProgram.php seems not to work.
Georg

**Comment by thetrueavatar** [comment]
Well the best bet is to call the getAllFeatures method. This one would
contains everything.provide me the result and I could check when I got some
time.

**Comment by JungeG** [comment]
Have created a GetAllFeatures.php with looks like

`#!/usr/bin/php <?php include __DIR__.'/bootstrap.php'; echo $viessmannApi->getAllFeatures();`

Get following error message:

> ./GetAllFeatures.php
PHP Fatal error:  Uncaught Error: Call to undefined method Viessmann\API\ViessmannAPI::getAllFeatures() in /etc/openhab2/scripts/viessmann/GetAllFeatures.php:4
Stack trace:
#0 {main}

Please advice.
Georg

**Comment by thetrueavatar** [comment]
My advice would be to read the doc  ;-):
https://htmlpreview.github.io/?https://raw.githubusercontent.com/thetrueavatar/Viessmann-Api/develop/docs/class-Viessmann.API.ViessmannAPI.html#_getFeatures

**Comment by JungeG** [comment]
Sorry Claude,
I didn't see the document before.
please find attached the getFeatures Messages
[20181205 Viessmann GetAllFeatures.docx](https://github.com/thetrueavatar/Viessmann-Api/files/2650416/20181205.Viessmann.GetAllFeatures.docx)

Still the call for ./ActivateEcoProgram.php - gives errors.

> PHP Fatal error:  Uncaught Viessmann\API\ViessmannApiException: Unable to set data for featureheating.circuits.0.operating.programs.ecoand action activate and data{"temperature":"18"}
 Reason: DEVICE_COMMUNICATION_ERROR in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php:769
Stack trace:
#0 phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(194): Viessmann\API\ViessmannAPI->setRawJsonData('heating.circuit...', 'activate', '{"temperature":...')
#1 /etc/openhab2/scripts/viessmann/ActivateEcoProgram.php(4): Viessmann\API\ViessmannAPI->activateEcoProgram(18, 0)
#2 {main}
  thrown in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php on line 769

What else can I test?
Thanks Georg

**Comment by thetrueavatar** [comment]
From your file you have indeed 2 circuit: 0 and 1.
For circuit 0
 "actions": [
        {
          "method": "POST",
          "isExecutable": true,
          "href": "
https://api.viessmann-platform.io/operational-data/installations/57217/gateways/7555115615614109/devices/0/features/heating.circuits.0.operating.programs.eco/activate
",
          "name": "activate",
          "title": "activate",
          "fields": [
            {
              "name": "temperature",
              "required": false,
              "type": "number",
              "min": 3,
              "max": 37,
              "stepping": 1
            }
          ],
          "type": "application/json"
        },
        {
          "method": "POST",
          "isExecutable": true,
          "href": "
https://api.viessmann-platform.io/operational-data/installations/57217/gateways/7555115615614109/devices/0/features/heating.circuits.0.operating.programs.eco/deactivate
",
          "name": "deactivate",
          "title": "deactivate",
          "fields": [],
          "type": "application/json"
        }
      ]
    }

For circuit 1:
"actions": [
        {
          "method": "POST",
          "isExecutable": true,
          "href": "
https://api.viessmann-platform.io/operational-data/installations/57217/gateways/7555115615614109/devices/0/features/heating.circuits.1.operating.programs.eco/activate
",
          "name": "activate",
          "title": "activate",
          "fields": [
            {
              "name": "temperature",
              "required": false,
              "type": "number",
              "min": 3,
              "max": 37,
              "stepping": 1
            }
          ],
          "type": "application/json"
        },
        {
          "method": "POST",
          "isExecutable": true,
          "href": "
https://api.viessmann-platform.io/operational-data/installations/57217/gateways/7555115615614109/devices/0/features/heating.circuits.1.operating.programs.eco/deactivate
",
          "name": "deactivate",
          "title": "deactivate",
          "fields": [],
          "type": "application/json"
        }
      ]

In practice with the api, you just have to pass the temperature and the
circuitId:
$viessmannApi->activateEcoProgram("20",0); // for circuit 0
$viessmannApi->activateEcoProgram("20",1); // for circuit 1

I can't help you anymore with this since I don't have eco program on my own
viessmann.

**Comment by JungeG** [comment]
Just to summarize:
still the same error message.
