### ISSUE TITLE
Error with GetRoomTemperature

### ISSUE THREAD

**Issue by Philippe-M** [thetrueavatar/Viessmann-Api#13]
Lorsque je veux ajouter une commande pour récupérer la température du thermostat d'ambiance j'ai l'erreur 

`Erreur dans l'exécution du terminal, la valeur retournée est : 255. Détails : Array ( [0] => PHP Fatal error: Uncaught TomPHP\Siren\Exception\NotFound: Property "value" was not found. in phar:///var/www/html/plugins/script/core/ressources/viessmann/Viessmann-Api-0.3.phar/vendor/tomphp/exception-constructor-tools/src/ExceptionConstructorTools.php:27 Stack trace: #0 phar:///var/www/html/plugins/script/core/ressources/viessmann/Viessmann-Api-0.3.phar/vendor/tomphp/siren/src/Exception/NotFound.php(32): TomPHP\Siren\Exception\NotFound::create('Property "%s" w...', Array, 1) #1 phar:///var/www/html/plugins/script/core/ressources/viessmann/Viessmann-Api-0.3.phar/vendor/tomphp/siren/src/Entity.php(144): TomPHP\Siren\Exception\NotFound::forProperty('value') #2 phar:///var/www/html/plugins/script/core/ressources/viessmann/Viessmann-Api-0.3.phar/src/API/ViessmannAPI.php(86): TomPHP\Siren\Entity->getProperty('value') #3 /var/www/html/plugins/script/core/ressources/viessmann/GetRoomTemperature.php(3): Viessmann\API\ViessmannAPI->getRoomTemperature() #4 {main} thrown in phar:///var/www/html/plugins/script/core/ressources/viessmann/Viessmann-Api-0.3.phar/vendor/tomphp/exception-constructor-tools/src/ExceptionConstructorTools.php on line 27 ) `

Alors que je n'ai pas de problème pour getOutSideTemperature, getBoilerTemperature, getActiveMode

J'ai un Vitoconnect 100 OPTO1 sur un Boiler Vitorondens 200-T

**Comment by Philippe-M** [comment]
J'ai trouvé il m'a suffit de changer le deviceId dans le fichier bootstrap.php.

**Comment by thetrueavatar** [comment]
Oui hélas la gestion des erreurs chez viessmannApi n'est pas toujours
cohérente. Alors que le Feature est pas dispo sur le circuitId il renvoye
parfois un json sans value, parfois l'erreur FEATURE_NOT_FOUND. Néanmoins,
je devrais faire de la programmation un peu plus défensive en vérifiant la
présence du champ.
