### ISSUE TITLE
Problem with Authorization with 1.0.1 since 11.07.

### ISSUE THREAD

**Issue by mrzino** [thetrueavatar/Viessmann-Api#21]
Api 1.0.1 was nicely working until 11.07. Then it stopped working caused by a Authorization issue. I looked into it today and could resolve the issue by adding this function to ViessmannOauthService.php:

public function getAuthorizationMethod()
{
        return static::AUTHORIZATION_METHOD_HEADER_BEARER;
}

**Comment by thetrueavatar** [comment]
Thanks for notifying me. However it has already been fixed in 1.1.0 version
and 1.2.0- snapshot.
Regards,

**Comment by mrzino** [comment]
Oops - sorry. Didn't see the update. Thanks for the quick reply.
