### ISSUE TITLE
[SetOneTimeCharge]  produces Error

### ISSUE THREAD

**Issue by JueBag** [thetrueavatar/Viessmann-Api#26]
Hi,
the procedure SetOneTimeCharge produces the following Error:

```
Unable to set data for featureheating.dhw.oneTimeCharge and action activate and data{"mode": "activate"}
	 Reason: DEVICE_COMMUNICATION_ERROR
Code: 1
Trace:#0 phar:///etc/openhab2/scripts/Viessmann-Api-1.2.0-SNAPSHOT.phar/src/API/ViessmannAPI.php(921): Viessmann\API\ViessmannAPI->setRawJsonData('heating.dhw.one...', 'activate', '{"mode": "activ...')

#1 /etc/openhab2/scripts/SetOneTimeCharge.php(3): Viessmann\API\ViessmannAPI->startOneTimeDhwCharge()

#2 {main}
```

I used the 1.2 0 snapshot version from the examples .
I have read the closed issue #19, the changed code seems to be in the snaspshot, however the result is faulty again.

**Comment by thetrueavatar** [comment]
Hello,
DEVICE_COMMUNICATION_ERROR is usually a problem of communication with vitoconnect.
However, I think there was also a problem with this method return the same error. I have fixed the bug but since I have recently accepted a pull request I wonder if there isn't kind of regression. Could you do the test with version 1.1.0 and 1.2.0(not snapshot one) ?

**Comment by JueBag** [comment]
Thanks for the feedback.
Here are the traces for  Version 1.2
```
2019-11-27 16:58:02.414 [INFO ] [eclipse.smarthome.model.script.Alarm] - result: Message: 
	 Unable to set data for featureheating.dhw.oneTimeCharge and action activate and data{"mode": "activate"}
	 Reason: DEVICE_COMMUNICATION_ERROR
Code: 1
Trace:#0 phar:///etc/openhab2/scripts/Viessmann-Api-1.2.0.phar/src/API/ViessmannAPI.php(921): Viessmann\API\ViessmannAPI->setRawJsonData('heating.dhw.one...', 'activate', '{"mode": "activ...')

#1 /etc/openhab2/scripts/SetOneTimeCharge.php(3): Viessmann\API\ViessmannAPI->startOneTimeDhwCharge()
#2 {main}
```

and Version 1.1:
```
2019-11-27 17:00:02.979 [INFO ] [eclipse.smarthome.model.script.Alarm] - result: Message: 
	 Unable to set data for featureheating.dhw.oneTimeCharge and action activate and data{"mode": "activate"}
	 Reason: DEVICE_COMMUNICATION_ERROR
Code: 1
Trace:#0 phar:///etc/openhab2/scripts/Viessmann-Api-1.1.0.phar/src/API/ViessmannAPI.php(822): Viessmann\API\ViessmannAPI->setRawJsonData('heating.dhw.one...', 'activate', '{"mode": "activ...')
#1 /etc/openhab2/scripts/SetOneTimeCharge.php(3): Viessmann\API\ViessmannAPI->startOneTimeDhwCharge()
#2 {main}
```
I'm using the StartOneTimeCharge.php from your examples folder. Using the isOneTimeDhwCharge() method  alone is working.

**Comment by thetrueavatar** [comment]
Hum, that's weird because I have checked and never changed this part of the code since june where somebody told me it was ok. I can't test it myself since I don't have the feature myself.
Could you try the call `$viessmannApi->getRawJsonData("heating.dhw.oneTimeCharge");` and provide me the result  ? So I can check if there is something that as changed on viessmann server

**Comment by JueBag** [comment]
I'm this result:

`2019-11-28 07: 55: 49.724 [INFO][.eclipse.smarthome.model.script.Test] - Ergebnis: {"links": [{"rel": ["self"], "href": "https://api.viessmann-platform.io/operational -Daten / V1 / Installation / 137038 / Gateways / 7571381700298105 / devices / 0 / Funktionen / heating.dhw.oneTimeCharge "}, {" rel ": [" up "]," href ":" https: //api.viessmann -platform.io/operational-data/v1/installations/137038/gateways/7571381700298105/devices/0/features"},{"rel":["http://schema.viessmann.com/link-relations#live- Updates "" https://wiki.viessmann.com/display/VPL/Relations#Relations-live-updates "]" href ":" / Betriebsdaten / Installation / 137038 / Gateways / 7571381700298105 / devices / 0 / Funktionen / heating.dhw.oneTimeCharge "}]," Klasse ": [" heating.dhw.oneTimeCharge "" Funktion „],"Eigenschaften": { "aktiv": { "Wert": false, "type": "boolean"}} "Entitäten": [{ "rel": [ „http://schema.viessmann.com/link- Beziehungen # Feature-Meta-Informationen "" https://wiki.viessmann.com/display/VPL/Relations#Relations-feature-meta-information "" https://wiki.viessmann.com/display/VPL/ Beträge Beträge # -einzigartige "]," Eigenschaften ": {" APIVERSION ": 1" uri ":" / v1 / Gateways / 7571381700298105 / devices / 0 / features / heating.dhw.oneTimeCharge "" gatewayId ":" 7571381700298105 "" Feature ":" heating.dhw.oneTimeCharge "" Zeitstempel ":" 2019-11-27T08: 00: 55.603Z "" isEnabled ": true," isReady ": true," Deviceid ":" 0 " }}], "Aktionen": [{ "Methode": "POST "" isExecutable ": true," href ":" https://api.viessmann-platform.io/operational-data/v1/installations/137038/gateways/7571381700298105/devices/0/features/heating.dhw. oneTimeCharge / Aktivieren "" Name "" Aktivieren "" title ":" Aktivieren "" Felder "[]" type ":" application / JSON "}, {" Methode ":" POST "" isExecutable ": false," href ":" https://api.viessmann-platform.io/operational-data/v1/installations/137038/gateways/7571381700298105/devices/0/features/heating.dhw.oneTimeCharge/deactivate " "name": "deaktivieren", "title": "deaktivieren", "Felder" [] "type": "application / JSON"}]}`
The initialy displayed english "result" got tranformed to the german "Ergebnis" after a second, never seen that.

**Comment by thetrueavatar** [comment]
Hum things haven't changed. I have asked to someone who test it on june to
see if it's still working.
Regards,


Le jeu. 28 nov. 2019 à 07:59, Jürgen Baginski <notifications@github.com> a
écrit :

**Comment by JueBag** [comment]
PR #28 solved this one.
