### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by irek74** [thetrueavatar/Viessmann-Api#27]
Hello,
I found this API very interesting. I own Viessmann equipment and I would like to combine heating system with my home automation application (domoticz on RPI) using python. The main issue is that I don't know how to start. Informations provided by this repository are very advanced and simple tutorial (like "Hello world") is missing. Is there a chance to create something for beginners like (one or two pages):
- prerequisties (what should be installed and in which order),
- in which file should be entered credentials (user name, password, etc)
- simple php file to run one function like: getFeatures() - to confirm that all of this really works.
I think that will make many more people interested in this topic.
Regards
Irek

**Comment by thetrueavatar** [comment]
Well I have written a documentation on the wiki wich I consider as the Tutorial you requires:
https://github.com/thetrueavatar/Viessmann-Api/wiki/English

**Comment by irek74** [comment]
Yes you did and I have seen it. In my opinion (you may disagree) it's addressed more to professional programmers than to hobbyist. Unfortunately I belong to the second group and your tutorial isn't clear enought to me (maybe because php is not my strongest asset ;-). Anyway, thank you for your effort at creating Viessmann API.
Regards
Irek

**Comment by irek74** [comment]
OK, after careful reading of your tutorial, I'm able to connect to Viessmann server using my credentials. I can read some basic data like outside temperature, power consumption, etc. I also receive many warnings for function GetAllInformation() and I don't know how to switch between circuits (0 and 1) to read data like shift and slope for each circuit, but it's a big step forward for me. Now I'm able to ask precise questions.
Regards
Irek

**Comment by thetrueavatar** [comment]
Most of the method have "circuitId" as optional parameter. By default circuit is 0 but you can overwritte it by passing the circuitId on the method:
`echo $viessmannApi->getShift(1);
echo $viessmannApi->getSlope(1);
`
Please have a look at method documentation here:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/thetrueavatar/Viessmann-Api/develop/docs/classes/Viessmann.API.ViessmannAPI.html

**Comment by irek74** [comment]
Thank you. I'll do more tests at the evening.

**Comment by thetrueavatar** [comment]
I did some "cleanup" on the wiki section to make things more understable for less technical people. If you have time to check and provide me your feedback.

**Comment by irek74** [comment]
Looks much better. If I may suggest something: maybe it's a good idea to include a "step by step" manual to get first results? Something like this:
1.	Update Raspberry PI
sudo apt-get update
sudo apt-get upgrade
2.	Install PHP
sudo apt install php7.0
sudo apt-get install php-curl
3.	Clone repository
git clone https://github.com/thetrueavatar/Viessmann-Api.git
4.	Enter credentials
cd /home/pi/Viessmann-Api/example
sudo nano credentials.properties
5.	Install composer
cd /home/pi/Viessmann-Api
curl -sS https://getcomposer.org/installer | php
php composer.phar install
cd /home/pi/Viessmann-Api/script
./createPhar.sh
6.	Perform simple test
cd /home/pi/Viessmann-Api/example
php GetOutsideTemperature.php

Regards
Irek

**Comment by Philippe-M** [comment]
Add require php 7.2

**Comment by Seba0855** [comment]
> Looks much better. If I may suggest something: maybe it's a good idea to include a "step by step" manual to get first results? Something like this:
> 
> 1. Update Raspberry PI
>    sudo apt-get update
>    sudo apt-get upgrade
> 2. Install PHP
>    sudo apt install php7.0
>    sudo apt-get install php-curl
> 3. Clone repository
>    git clone https://github.com/thetrueavatar/Viessmann-Api.git
> 4. Enter credentials
>    cd /home/pi/Viessmann-Api/example
>    sudo nano credentials.properties
> 5. Install composer
>    cd /home/pi/Viessmann-Api
>    curl -sS https://getcomposer.org/installer | php
>    php composer.phar install
>    cd /home/pi/Viessmann-Api/script
>    ./createPhar.sh
> 6. Perform simple test
>    cd /home/pi/Viessmann-Api/example
>    php GetOutsideTemperature.php
> 
> Regards
> Irek

It would be great to see that step by step guide in documentation of the API as it was very helpful for me. It's easy to understand for beginners and it clearly shows what to do to make this work properly.
