### ISSUE TITLE
gatewayID & installationID

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#31]
Hi,
thanks for developing new versions for the VIESSMANN-API.
I was searching for gatewayID & installationID in the ViCare App, but couldn't find it - do you have a hint where to look it up?
Thanks Georg

**Comment by thetrueavatar** [comment]
I have just implement on 1.4.0-SNAPSHOT the getGatewayId and
getInstallationId. I had to do some refactoring so if you could check that
everything is still fine.
Regards,


Le ven. 20 mars 2020 à 08:29, Georg Jungermann <notifications@github.com> a
écrit :

**Comment by JungeG** [comment]
Hi Claude,
If I try to run the modified bootstrap.php - I get following error message:

> PHP Notice:  Undefined offset: 2 in /etc/openhab2/scripts/viessmann/bootstrap.php on line 13
PHP Notice:  Undefined offset: 3 in /etc/openhab2/scripts/viessmann/bootstrap.php on line 14
Message: syntax error, unexpected '?'
Code: 0

Still I don't know where to find gatewayID & installationID
Thanks for your help
Georg

**Comment by thetrueavatar** [comment]
Which version of the par are you using ? This is available for version
1.4.0-SNAPSHOT and 1.3.2. Moreover, you'll to update the bootstrap.php.
I have added an example to get those
value example/GetInstallationInformation.php.
regards

Le ven. 20 mars 2020 à 11:23, Georg Jungermann <notifications@github.com> a
écrit :

**Comment by JueBag** [comment]
Getting the IDs is working like a charm!

**Comment by JungeG** [comment]
I was using 1.4.0-SNAPSHOT.
I tried to get Installation Information with GetInstallationInformation.php. using 1.3.1.phar:

> Message: Call to undefined method Viessmann\API\ViessmannAPI::getInstallationId()
Code: 0
I don't find 1.3.2.phar only the source code.
Thanks for help
Georg

**Comment by JungeG** [comment]
> Getting the IDs is working like a charm!

Which version of the API are you using?

**Comment by thetrueavatar** [comment]
1.3.2 is now available. I had to do a small fix before. Please notre I haave swapped gatewayId and installationId order. credentials.properties should contain:
* username
* password
* installationId
* gatewayId

**Comment by JungeG** [comment]
Thanks!
my bootstrap.php is like this

`include 'phar://' . __DIR__ . '/Viessmann-Api-1.3.2.phar/index.php';

$credentials = file(__DIR__ . "/credentials.properties");
$params = [
    "user" => trim("$credentials[0]"),
    "pwd" => trim("$credentials[1]"),
//    "installationId" =>trim("$credentials[2]"),
//    "gatewayId" =>trim("$credentials[3]"),
//    "deviceId" => "0",
//    "circuitId" => "0"
];`

my GetinstallationInformation.php is:

`<?php
include __DIR__.'/bootstrap.php';
echo "InstallationId: ".$viessmannApi->getInstallationId()."\n";
echo "GatewayId: ".$viessmannApi->getGatewayId();`

now I get following error message:

> Message: syntax error, unexpected '?'
Code: 0

Any idea what is wrong?
Thanks Georg

**Comment by thetrueavatar** [comment]
I have noticed in your previous post there was a closing tag ?> which is a
syntax error. I have also used a return type ?Entity which requires php
7.1.0 a least. Could you check your version ?

Le ven. 20 mars 2020 à 18:04, Georg Jungermann <notifications@github.com> a
écrit :

**Comment by JungeG** [comment]
Hi,
i have upgraded to 

> php -v
PHP 7.1.20-1+b2 (cli) (built: Aug  3 2018 03:45:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.20-1+b2, Copyright (c) 1999-2018, by Zend Technologies

if I call GetinstallationInformation.php following error message:

> PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 48
PHP Notice:  Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 72
PHP Notice:  Use of undefined constant CURLOPT_HTTPHEADER - assumed 'CURLOPT_HTTPHEADER' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 73
PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 74
PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 75
PHP Notice:  Use of undefined constant CURLOPT_USERPWD - assumed 'CURLOPT_USERPWD' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 76
PHP Notice:  Use of undefined constant CURLOPT_HTTPAUTH - assumed 'CURLOPT_HTTPAUTH' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 77
PHP Notice:  Use of undefined constant CURLAUTH_BASIC - assumed 'CURLAUTH_BASIC' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 77
PHP Notice:  Use of undefined constant CURLOPT_POST - assumed 'CURLOPT_POST' in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-1.3.2.phar/src/Oauth/ViessmannOauthClientImpl.php on line 78
Message: Call to undefined function Viessmann\Oauth\curl_init()
Code: 0

Sorry, but I have no idea how to solve this problem.
Georg

**Comment by thetrueavatar** [comment]
Have you installed/upgrade php-curl ?

Le ven. 20 mars 2020 à 21:28, Georg Jungermann <notifications@github.com> a
écrit :

**Comment by JungeG** [comment]
Sorry - I have upgraded to php7.1-curl now it seems to work.
Which version are you proposing 1.3.2. or 1.4.0-SNAPSHOT?
Thanks Georg

**Comment by thetrueavatar** [comment]
1.3.2 is the release/stable,  snapshot version  contains more functionality
but it's less stable.


Le ven. 20 mars 2020 à 21:39, Georg Jungermann <notifications@github.com> a
écrit :

**Comment by JungeG** [comment]
Thanks Claude,
I will stay on 1.3.2. until you recommend to upgrade.
Georg
