### ISSUE TITLE
Class 'Viessmann\API\proxy\impl\ViessmannApiException' not found

### ISSUE THREAD

**Issue by dsgrafiniert** [thetrueavatar/Viessmann-Api#32]
With the following script, I am getting an error. What am I doing wrong.

`Message: Class 'Viessmann\API\proxy\impl\ViessmannApiException' not found`

Code Snippet:
```
<?php
include __DIR__.'/bootstrap.php';

use Viessmann\API\ViessmannApiException;

try {
    $viessmannApi->setDhwTemperature("57");
    $viessmannApi->startOneTimeDhwCharge();
} catch (ViessmannApiException $e) {
    echo "Message: " . $e->getMessage() . "\n";
    echo "Code: " . $e->getCode() . "\n";
    echo "Trace:" . $e->getTraceAsString() . "\n";
}

?>
```

I am using 1.4.0-SNAPSHOT

**Comment by thetrueavatar** [comment]
Which version ? I have forgotten to import the exception in older version

Le ven. 20 mars 2020 à 12:08, Dominik Schön <notifications@github.com> a
écrit :

**Comment by dsgrafiniert** [comment]
I am relying on the compiled phar in the examples folder.
In my Dockerfile I am executing the following commands:

```
RUN git clone -b develop https://github.com/thetrueavatar/Viessmann-Api.git
COPY --from=builder /tmp/Viessmann-Api/example/*.phar .
```

**Comment by thetrueavatar** [comment]
There was still a missing import. However, this exception is throw when you
have a problem(In my test I don't have the feature for instance).
I have pushed the update.
Regards,

Le ven. 20 mars 2020 à 12:21, Dominik Schön <notifications@github.com> a
écrit :
