### ISSUE TITLE
Adding gatewayId and installationId results in UNSUPPORTED_GATEWAY_TYPE

### ISSUE THREAD

**Issue by dsgrafiniert** [thetrueavatar/Viessmann-Api#33]
I just extracted installationId and gatewayId via the just integrated Getters and added them to the credentials.properties

After adding them, I get the following Error Message

```
Message: Unable to get data for feature 
Reason: UNSUPPORTED_GATEWAY_TYPE
Code: 1
```

**Comment by thetrueavatar** [comment]
I have swapped installationId and gatewayId.  Please define first
installation and then gateway

Le ven. 20 mars 2020 à 12:18, Dominik Schön <notifications@github.com> a
écrit :
