### ISSUE TITLE
getAvailableFeatures() does not work

### ISSUE THREAD

**Issue by galaxis1309** [thetrueavatar/Viessmann-Api#35]
Hi,
trying to pull some fuelcell information under:
HEATING_FUELCELL_SENSORS_TEMPERATURE_RETURN = "heating.fuelcell.sensors.temperature.return";
Therefore i tried the getAvailableFeatures(), which gives me the error message:
Message: Call to a member function getEntities() on null
Code: 0
Can somone help please ?
Thanks
galaxis1309

**Comment by thetrueavatar** [comment]
should be fixed right now in 1.4.0-SNAPSHOT. Could you test please ?

**Comment by thiborg** [comment]
Hi,
i've just tested it.
Now it's working.

Thanks a lot
Thorsten

**Comment by galaxis1309** [comment]
Hi,
many thanks for this instant fix; great job.
Martin
