### ISSUE TITLE
error during creating new feature with 1.4.0

### ISSUE THREAD

**Issue by galaxis1309** [thetrueavatar/Viessmann-Api#36]
Hi,
still trying to build a new feature:
**added in ViessmannFeature.php:**
const HEATING_FUELCELL_SENSORS_TEMPERATURE_RETURN = "heating.fuelcell.sensors.temperature.return";

**added in ViessmannAPI.php**
    /**
     * @return string of BSZ return temperature if available
     * @throws ViessmannApiException
     */

    public function getFuelcellReturnTemperature(): string
    {
        return $this->getEntity(ViessmannFeature::HEATING_FUELCELL_SENSORS_TEMPERATURE_RETURN)->getProperty("value")["value"];
    }
**created new phar, tried to use this feature with :**
<?php
include __DIR__.'/bootstrap.php';
echo $viessmannApi->getFuelcellReturnTemperature();

got error message:
 php mpGetAvailableFeatures.php
Message: Call to undefined method Viessmann\API\ViessmannAPI::getEntity()
Code: 0

Can someone help please ?
Thanks.
Martin

**Comment by thetrueavatar** [comment]
use $this->viessmannFeatureProxy->getEntity instead of $this->getEntity as I had to move this method for caching.

**Comment by galaxis1309** [comment]
hi, many thanks, this perfectly works, will implement some fuelcell festure and let you know afterward. great project !!
