### ISSUE TITLE
Want to read value from heating.primaryCircuit.sensors.temperature.return,

### ISSUE THREAD

**Issue by thiborg** [thetrueavatar/Viessmann-Api#37]
Hello,

i'm a complete noob to php. 
I'm missing the primaryReturnTemperature within the features. 

So i've copied and modified the ViesmannAPI.php

ViessmannFeature::HEATING_PRIMARYCIRCUIT_SENSORS_TEMPERATURE_SUPPLY
to 
ViessmannFeature::HEATING_PRIMARYCIRCUIT_SENSORS_TEMPERATURE_RETURN

I've added the feature in the ViessmannFeature.php as well.

I've not compiled anything, just modified the php files.
When I try to call then function I get:

@Message: Call to undefined method Viessmann\API\ViessmannAPI::getHeatingPrimaryCircuitTemperatureReturn()

what point i'm missing?
thanks for your help
Thorsten

**Comment by thetrueavatar** [comment]
You have to rebuild the phar which is a kind of zip file containing all php file.
In the root directory
`php -d phar.readonly=0 phar-builder.phar package -n composer.json`

**Comment by thetrueavatar** [comment]
If you have to test and retry you may use bootstrap-dev.php instead of bootstrap.php which will use php file from src instead of php files from the phar.
