### ISSUE TITLE
Get Vitoconnect 100 status information

### ISSUE THREAD

**Issue by smhex** [thetrueavatar/Viessmann-Api#38]
Hi,

I am wondering if the status information from Vitoconnect 100 is also accessible via your API. At least the web portal shows signal strength and the firmware version in addition to the gateway id. I looked through the json test files but did'nt found something which points in that direction.

Do you have an idea to get those values?

Thanks!

**Comment by thetrueavatar** [comment]
Ok by digging into the vitoguide app I have discovered there is a way to get all information about gateway status:
https://api.viessmann-platform.io/operational-data/v2/installations/XXX/gateways/XXXX/features/gateway
and for your very own request https://api.viessmann-platform.io/operational-data/v2/installations/XXX/gateways/XXX/features/gateway.wifi which provide you the asked value.
My code currently is adding /device/device_id to every url such as 
operational-data/installations/XXXX/gateways/XXX/devices/0/features/gateway 
so I should to some little modification to be able to get those value. Will do when I have some free time.

**Comment by thetrueavatar** [comment]
I have just done a quick & dirty dev with 5 methods on SNAPSHOT version. They return raw json and don't do any caching. It's just for testing not for "production". Could you try it ?
echo $viessmannApi->getGatewayWifi()."\n";
echo $viessmannApi->getGatewayBmuconnection()."\n";
echo $viessmannApi->getGatewayDevices()."\n";
echo $viessmannApi->getGatewayFirmware()."\n";
echo $viessmannApi->getGatewayStatus()."\n";

**Comment by smhex** [comment]
Thank you. I hope I am able to test it tomorrow. Do you need the raw json output?

**Comment by thetrueavatar** [comment]
No need. Just check that raw data are fine. I will refine methods afterward.

**Comment by smhex** [comment]
Just checked the returned data. Looks pretty good so far. Even there are some actions to reboot or to update the firmware of the gateway. I also got some information about my heating device. However, "modelId", "version" and "name" look very Viessmann specific.

**Comment by smhex** [comment]
Issue solved
