### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by sipiyou** [thetrueavatar/Viessmann-Api#42]
I am not able to login to my account.

I am using the same credentials (email + pwd) which I use for the vitoconnect app as well as logging into this url:

https://vitoguide.viessmann.com/home

This is the curl-response to ViessmannOauthClientImpl.php::getCode() Call:

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<HTML>
<HEAD>
<TITLE>Error Page</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF">
<CENTER><H2>
ERROR!: error class 'Client Error'; error code '400'; error text 'bad request'
</H2></CENTER>
</BODY></HTML>
`

--------------------

which leads the api to throw an exception that user/password is invalid.

I have tried latest version from git (1.4-snapshot) as well as 1.3.2+1.3.3 with the same result.

My credential file has only 2 entries, first line is the email adress and the second one is the password (all unix-style).

I am using php 7.2, this is the output for phpinfo:

[php7-info.txt](https://github.com/thetrueavatar/Viessmann-Api/files/5081268/php7-info.txt)

Please help :)

**Comment by sipiyou** [comment]
Can someone help me on this, please ? I am still not able to login.

When I use iobroker module, it works with the same credentials. Please HELP!

**Comment by sipiyou** [comment]
@thetrueavatar: Can you please contact me directly by email ? I will send you my credentials so you can check what is wrong.
Unfortunately, I cannot contact you personally on github and I also don't have your email.

**Comment by thetrueavatar** [comment]
Here is mine: thetrueavatar@gmail.com. However it will be best effort
support as it's a personal project and I'm kind of busy for the moment.
Please note, that usually I don't provide custom support.
Regards
