### ISSUE TITLE
Support for new Smart Climate components

### ISSUE THREAD

**Issue by smhex** [thetrueavatar/Viessmann-Api#43]
Hi,

Viessmann recently announced the release of their new smart climate components. I bought a thermostat for testing purposes. It runs smoothly and can be configured within Vicare and the web portal. I called getAvailableFeatures() on the API to see how its data is mapped. Unfortunately, no additional/new entities are available. Do you have an idea where to look for the data?

Best regards
smhex

**Comment by thetrueavatar** [comment]
Well, the best bet would be to use a program to sniff how ViCare gets those
values. I do use Packet Capture.
However, if you want to stick to my viessman api  you could try to get the
raw json data with $viessmannApi->getRawJsonData("").
The method getAvailableFeature only return feature if there is a properties
field. Maybe that the climate components doesn't have properties.
Regards,

**Comment by adorobis** [comment]
> I bought a thermostat for testing purposes. It runs smoothly and can be configured within Vicare and the web portal.

Which viessmann gateway do you need to work with the new thermostats and sensors?

**Comment by smhex** [comment]
As long as you don't have a heating system with inbuilt support for ViCare you most probably need a Vitoconnect OPTO2 to communicate with the smart climate components. I had to replace my OPTO1 gateway for this...

Regards
smhex

**Comment by adorobis** [comment]
@smhex thanks! Did you have any luck with discovering the API to sense/control those new sensor and thermostat devices?

**Comment by smhex** [comment]
Not yet. Did not have the time to dig deeper into this. Is on my plan for the time around Christmas/New Year😀

**Comment by fdebrus** [comment]
This what I've found to-date on the topic

Listing the entities from your installation will provide you with all the zigbee ID for Sensors, Repeaters and Actuators

Then you can query values for those ID like (eg temperature reported by the zigbee device)

`https://api.viessmann-platform.io/iot/v1/equipment/installations/<installationID>/gateways/<gatewayID>/devices/zigbee-<zigbeeID>/features/cs.sensors.temperature`

Other values are also available 

cs.sensors.humidity
device.roomId
device.heatingCircuitId
device.power.battery
...

Hope this helps

It takes time to revert the API. Hopefully, Viessmann will make it public soon :-)

**Comment by thetrueavatar** [comment]
Well, I have access to their public api. Don't expect to have exhaustive
data. Can't find any informaton about zigbee devices.
There is no official contract defining the kind of devices supported so
everybody should discover their own feature....
