### ISSUE TITLE
ban test

### ISSUE THREAD

**Issue by EricChanussot** [thetrueavatar/Viessmann-Api#44]
Bonjour,
Je joue un peu avec ma chaudière Viessmann et le script de ldb2000 que vous semblé bien connaitre.

https://github.com/ldb2000/Viessman-API/blob/master/php/viessmann.php

Je cherche à implémenter la gestion du ban sur ce script comme vous l'avez fait dans votre api
Quelque chose du genre:

` 
$dec = json_decode;
 if(array_key_exists( 'statusCode', $dec)) {
    $statusCode = $dec['statusCode'];
    $message = $dec['message'];
    switch($statusCode) {
      case 429: {
        $bannedTimeReset = round($dec['extendedPayload']['limitReset']/1000);
        fdebug("Error: $statusCode $message At ".date('Y-m-d H:i:s',$bannedTimeReset)); 
      }
    }
    exit();
  }
`

N'étant pas développeur j'éprouve quelques difficultés.
Pourriez-vous m'aider?
Bien cordialement

**Comment by thetrueavatar** [comment]
Bonjour,
Voici la partie du code qui pourrait vous intéresser:

if (isset($data["statusCode"])) {
    if($data["statusCode"]=="429"){
        $epochtime=(int)($data["extendedPayload"]["limitReset"]/1000);
        $dt = new DateTime("@$epochtime");
        $resetDate=$dt->format(DateTime::RSS);
        throw new ViessmannApiException("\n\t Unable to read
installation basic information \n\t Reason: ". $data["message"]."
Limit will be reset on ".$resetDate, 2);
    }else{
        throw new ViessmannApiException("Unable to get data for
feature " . $resources . "\nReason: " . $data["message"], 1);
    }
}

Si le statusCode=429 alors ça veut dire qu'on est banni. Le limitReset est
exprimé en "epochtime"(nombre de ms depuis 1er janvier 1970) php s'attend à
un epochtime en seconde. C'est pourquoi j'ai divisé par 1000.
Ensuite j'utilise l'objet DateTime pour formatter la date sur base de
l'epochtime.

Bien à vous,

**Comment by EricChanussot** [comment]
Bonsoir,
J’avais remarqué ce code contenue dans ViessmannFeatureRemoteProxy.php
Mon souci est throw new ViessmannApiException que je ne parviens pas à adapter au code de Laurent
Pourriez-vous m’aider ?
Bien cordialement

**Comment by thetrueavatar** [comment]
désolé je n'ai déjà pas le temps de fournir un support rapide pour mon propre code alors celui des autres...
