### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by soeffi** [thetrueavatar/Viessmann-Api#45]
All,

until today, I had the ViessmannAPI up an running fine here, now it suddenly stopped working (no known changes on my end).

The error message is

```
Message: Unable to get data for feature 
Reason: Endpoint /operational-data/installations/[xxx]/gateways/[yyy]/devices/0/features/ does not match any existing route
Code: 1
```

I tried removing the cache functionality, to enable auto-discovery of gateway and installation ID. Then the error message changes to
```
Message: 
	 Unable to read installation basic information 
	 Reason: Endpoint /general-management/installations does not match any existing route
Code: 2
```

Is anyone else also experiencing issues or is it just me? Any ideas what the problem might be?

Edit: From ViCare App and Vitoguide I can access the device normally. I also tried rebooting the Gateway, which does not change anything.

**Comment by thetrueavatar** [comment]
Same for me. Guess that viessman has changed some stuff. I will check on
the german site to grab some info.
Regards

**Comment by soeffi** [comment]
Good to know that it's not just me. Do you have a link where you are looking for information? If it helps, I can try to help gathering information (which might be easier for me, speaking German natively - not sure if they provide english information as well)

**Comment by soeffi** [comment]
Well, actually it seems to work again, maybe Viessmann broke something on their end (the ViCare App was working normally however)...

Let me use this opportunity to ask something else: Do you know what the reason is, that the API is limited in the number of calls, but the ViCare App is still able to provide updates to the displayed values every few seconds?

**Comment by thetrueavatar** [comment]
Viessmann is developing an api to be used for home automation.
The current api is designed to be used by an application such as ViCare. So
there is not a permanent load on it since it mainly depends from the
customer action on the application. When the application is closed, there
is no more request on the api.
I have used this api for home automation but since it wasn't design for it
Viessmann as set a threshold to avoid too much load on it.
Best Regards,

**Comment by thetrueavatar** [comment]
Things are working as usual on my home automation.
Regards,


Le mar. 13 oct. 2020 à 10:51, thetrueavatar <thetrueavatar@gmail.com> a
écrit :

> Viessmann is developing an api to be used for home automation.
> The current api is designed to be used by an application such as ViCare.
> So there is not a permanent load on it since it mainly depends from the
> customer action on the application. When the application is closed, there
> is no more request on the api.
> I have used this api for home automation but since it wasn't design for it
> Viessmann as set a threshold to avoid too much load on it.
> Best Regards,

**Comment by soeffi** [comment]
Same for me, working just as before.

Being curious, do you think I would get banned from the interface also if I just keep ViCare App open for long enough to hit the short time limit, or is there some identification of the ViCare App going on, bypassing the limit somehow?

Looking forward to the new API, hopefully the limits can be raised even more (though it's ok for most of the use cases for now).

Thanks for you work!

**Comment by thetrueavatar** [comment]
no more problem to my knowledge
