### ISSUE TITLE
Authentication Error with 2 network interface cards

### ISSUE THREAD

**Issue by Bart1478** [thetrueavatar/Viessmann-Api#46]
Hi,

I have 2 ethernet interface's on a Ubuntu server. One ethernet interface (eth1) is connected to the local network. The second one (eth2) to the internet. If both interfaces are up the authentication process stops with an error. If i disable the interface connected to the local network (eth1) then the authentication process runs fine and I get some values from the heating system.
Is there a way to tell the API which network interface to use? 
some improvements on the API?

hope you can help!

kind regards

**Comment by thetrueavatar** [comment]
Well the api relies on php-curl. This is the only part which could be
related to how network interfaces are used.
There is a way to setup on php-curl a specific interface with env variable
CURLOPT_INTERFACE:

curl_setopt($ch, CURLOPT_INTERFACE, "XXX.XXX.XXX.XXX");

So maybe you should give a try by setting  CURLOPT_INTERFACE en var. I'm
not sure however if curl-php will use os env var. If not then, I should add
the possibility to set this variable.

Regards,

**Comment by Bart1478** [comment]
Solution: I had 2 network interfaces (NIC) one internal and one connected to the internet. Because there is no possibility to tell the API which NIC to choose (the one connected to the internet) there is a possibility on Ubuntu platform to modify the metric value of each network interface. This lower metric value the higher the IPv4 route priority. this metric value can be modified with the ifmetric package (ifmetric is a Linux tool for setting the metrics of all IPv4 routes attached to a given network interface at once. This may be used to change the priority of routing IPv4 traffic over the interface.Lower metrics correlate with higher priorities.)
