### ISSUE TITLE
Get and Set parameters as A0... & B0....

### ISSUE THREAD

**Issue by Ben13009** [thetrueavatar/Viessmann-Api#48]
Dear All,

First thing, is congratulation thetrueavatar for the API.
I have a question, i saw with infrared interface and vitalk on raspberry we can get the parameters as A0....B0...
Is it possible to do the same with the API? It should be goog to be able to disable or enable the frog program with A3 and A4 parameters.

Thanks in’advance

**Comment by thetrueavatar** [comment]
a bit late but viessman doesn't expose internal code. The only exception is the heating curve.
