### ISSUE TITLE
Jeedom plugin Viessmann

### ISSUE THREAD

**Issue by EricChanussot** [thetrueavatar/Viessmann-Api#50]
Bonjour thetrueavatar
Un plugin s'appuyant sur votre API a été développé sur https://community.jeedom.com/t/plugin-viessmann/51078.
Il semblerait que les unités de consommation gaz soit en m³ sur les nouvelles chaudières.
Unit: kilowattHour 
Unit: cubicMeter
Vous serait-il possible de voir pour implémenter cette fonctionnalité?
N'hésitez pas à nous solliciter si vous avez besoin de plus d'infos.
Bien cordialement

**Comment by thetrueavatar** [comment]
salut. Bon ben en fait c'est via github que j'ai eu la notification(ça n'a jamais marché sur le community.jeedom)....
Je n’ai pas encore regarder mais peux-tu déjà me dire sur quelle version te base-tu pour ton plugin(snapshot ou release) ?
N’ayant pas la mesure de consommation sur ma chaudière actuellement ça n’est pas toujours facile de valider. Si jamais tu peux me donner le nom de la méthode dans mon api et un exemple de réponse ça me ferait gagner du temps

**Comment by EricChanussot** [comment]
Salut,
Sachant que tu avais des problèmes avec les notifications sur jeedom je me suis permis d'essayer de te contacter depuis plusieurs endroits (github, domoticz ….) tu ne prendras pas peur :)
Le plugin est basé sur Viessmann-Api-1.4.0.phar qui est si je ne me trompe pas t'as dernière version.

Les features concernés sont:
heating.gas.consumption.heating
heating.gas.consumption.dhw

properties: day, week, month, year.

```
      "class": [
                "heating.gas.consumption.heating",
                "feature"
      ],
-
-	  
        "unit": {
          "value": "kilowattHour",
          "type": "string"
        }
```
Pour les nouvelles chaudières
`          "value": "cubicMeter",`

Si besoin n'hésite pas!

**Comment by thetrueavatar** [comment]
Si je comprend bien tu me demandes de retourner en plus de la valeur
l'unité de référence ?
Je préfère ajouter une méthode supplémentaire pour cela afin d'éviter de
casser la rétro-compatibilité.
Par contre, je n'ai pas de version 1.4.0. J'ai une 1.3.4(la stable) et une
1.4.0-SNAPSHOT, la work in progress.

**Comment by EricChanussot** [comment]
Oups désolé c'est bien la 1.4.0-SNAPSHOT.phar
Oui si tu as la possibilité de retourner l'unité de référence:

kilowattHour => kWh
cubicMeter => m³

Pas de problème pour l'ajout d'une méthode supplémentaire.

**Comment by thetrueavatar** [comment]
Au final, j'ai rajouté un booléen qui par défaut est à false. Si il est à
true alors ça renvoie un objet:
{"unit":"kilowattHour","value":[6.4,12.4,9,8.6,12.4,9.6,14,11.6]}

Je l'ai fait dans la version snapshot
Bien à toi,

**Comment by EricChanussot** [comment]
Je n'avais pas vu qu'une fonction avait été rajoutée en juillet 2020, j’ai dû recompiler le phar de la branche develop pour en disposer.

`$uniteGaz = $viessmannApi->getGenericFeaturePropertyAsJSON(ViessmannFeature::HEATING_GAS_CONSUMPTION_DHW, "unit");`

**Comment by thetrueavatar** [comment]
J'ai déjà recompilé le phar avant de push. Il est dans example.

**Comment by thetrueavatar** [comment]
Ceci est une méthode générique permettant en effet de récupérer le json
brut. C'est sans doute plus flexible pour ton plugin tandis que les autres
méthodes sont plutôt pour des utilisateurs novices.



Le mar. 16 févr. 2021 à 16:26, thetrueavatar <thetrueavatar@gmail.com> a
écrit :

> J'ai déjà recompilé le phar avant de push. Il est dans example.
>
>

**Comment by EricChanussot** [comment]
Je ne suis pas l’auteur du plugin, mais ayant beaucoup joué avec ton API sous jeedom et ayant la possibilité de tester sur plusieurs machines, j’essaie d’apporter mon aide afin qu’il soit compatible pour tous.
Nous teston est je reviendrais te dire se qu’il en est.
Merci pour t’as disponibilité.
