### ISSUE TITLE
Plugin Viessmann, Modes et Programmes

### ISSUE THREAD

**Issue by EricChanussot** [thetrueavatar/Viessmann-Api#51]
Bonjour,
Afin d'harmoniser l'interprétation des différant modes et programmes disponible pour chaque type de chaudière, j'aimerais proposer aux utilisateurs de ton API une façon simple de récupérer et de nous communiquer ces informations.
Dans mon cas ces informations sont:

**Les modes**
`["standby","dhw","dhwAndHeating","forcedReduced","forcedNormal"]`

**Les programmes**
`["active","comfort","eco","external","holiday","normal","reduced","standby"]`

Ces infos sont disponibles comme présenté dans le json, je ne sais pas trop comment les faire récupérer pas les utilisateurs de l'api (depuis jeedom ou SSH)?
Si tu as une idée un petit code PHP ou autre?

Bien a toi.
Eric

**Comment by EricChanussot** [comment]
Tu as apparemment déjà implémenté la méthode getFeatures() qui devrait me retourner le tableau de toutes les features en json.
Sur ton github:
https://github.com/thetrueavatar/Viessmann-Api/wiki/French
Le lien qui parle de cette méthode est mort.
Viessmann Api => http://htmlpreview.github.io/?https://github.com/thetrueavatar/Viessmann-Api/blob/develop/docs/namespace-Viessmann.API.html

**Comment by thetrueavatar** [comment]
Oui la doc semble mal générée.
Je regarderai à ça.
Claude

**Comment by EricChanussot** [comment]
J’ai tenté avec ViessmannFeature sans succès.

```
<?php
include __DIR__.'/bootstrap.php';
use Viessmann\API\ViessmannFeature;

echo "Liste des Modes " . $viessmannApi->getRawJsonData(ViessmannFeature::HEATING_CIRCUITS_0_OPERATING_MODES) . "\n";
```

**Comment by thetrueavatar** [comment]
Malheureusement, la liste n'est pas facilement accessible.
En bidouillant, il y a moyen mais c'est bof:

<?php

use TomPHP\Siren\Entity;
use Viessmann\API\ViessmannAPI;

include __DIR__.'/bootstrap.php';
$viessmannApi = new ViessmannAPI($params,false);
$data=json_decode($viessmannApi->getRawJsonData("heating.circuits.0.operating.modes"),true);
print_r(end(Entity::fromArray($data,
true)->getEntities())->getProperty("components"));

Pour info, je viens de recevoir un email de viessmann comme quoi ils
commencent enfin leur phase de test du portail pour leur api.
Mon projet en soit est un reverse-engeneering de leur service à destination
de ViCare+ un client pour rendre le tout facile.
Ici ils vont mettre une vrai API à destination d'appareil domotique.
S'ils font leur taf correctement sur leur API(via un openapi) alors mon
client n'aura plus de raison d'être.
Du coup, j'éviterais de trop investir dans des trucs complexes.

**Comment by EricChanussot** [comment]
T’as « bidouille » me convient tout à fait. Merci
J’ai ajouté la récupération des programmes sur le même script histoire de tous récupérer en même temps.
Il y a peut-être moyen de simplifier l’écriture ? ?

```
<?php

use TomPHP\Siren\Entity;
use Viessmann\API\ViessmannAPI;

include __DIR__.'/bootstrap.php';
$viessmannApi = new ViessmannAPI($params,false);
$MyModes=json_decode($viessmannApi->getRawJsonData("heating.circuits.0.operating.modes"),true);
$MyPrograms=json_decode($viessmannApi->getRawJsonData("heating.circuits.0.operating.programs"),true);

echo "Modes:\n";
echo "====\n";
print_r(end(Entity::fromArray($MyModes,true)->getEntities())->getProperty("components"));
echo "\n";

echo "Programs:\n";
echo "====\n";
print_r(end(Entity::fromArray($MyPrograms,true)->getEntities())->getProperty("components"));
echo "\n";
```

L’API permet-elle de récupérer le modèle de la chaudière ?

**Comment by thetrueavatar** [comment]
$viessmannApi->getGatewayDevices()

**Comment by nerixs** [comment]
Le fichier « gateway.devices.siren.json » me donne bien les informations de la feature (gateway.devices) notamment ce que je cherche à récupérer, le nom.
```
  "properties": {
    "devices": {
      "value": [
        {
          "id": "0",
          "fingerprint": "gg:20,gk:4b,si:11,esi:65535",
          "status": "online",
          "modelId": "CU401B_G",
          "modelVersion": "2017-07-20-12-50-18-952",
          "type": "heating",
          "name": "VT 200 (WO1C)"
        }
      ],
      "type": "DeviceList"
    }
  },
```
Je ne parviens pas isoler la méthode dont j’aurais besoin pour récupérer ce non.
Si tu en as le temps un peu d’aide serait la bienvenue.

**Comment by nerixs** [comment]
Bonsoir Claude,
Je ne parviens pas identifier les éléments de la feature "gateway.devices" nécessaires à la récupération du nom de la chaudière.
Peut tu m’orienter ?
Eric

**Comment by nerixs** [comment]
Le code donné plus haut, doit permettre aux utilisateurs de l’api de nous retourner le nom des modes et programmes telle qu’ils sont déclarés chez Viessmann.
Le non de la régulation permettra de recenser ces modes et programmes pour chaque modèle.
Dans mon cas pour une chaudière de type Vitodens 222W le nom de la régulation est (Vitodens 200 with HO1B).
Il restera après, soit via Vicare ou depuis la chaudière à récupérer les noms donnés à ces modes et programmes pour les déclarer dans le plugin.
A moins que tu connaisses une autre façon de procéder ?
Comme déjà dis, je ne suis pas développeur, j’essaie simplement d’apporter mon aide en apportant des éléments, dans le but d’enrichir ce plugin qui me semble très prometteur.
