### ISSUE TITLE
Plugin Viessmann, nouvelle fonction

### ISSUE THREAD

**Issue by PhilippeJ-code** [thetrueavatar/Viessmann-Api#52]
Bonjour,

Je suis l'auteur du plugin Viessmann sur Jeedom, un utilisateur du plugin me demande de pouvoir afficher l'historique des dysfonctionnements de la chaudière. Si vous voulez bien ajouter la fonction suivante à l'API, cela m'aiderait pour la récupération des infos.

`    public
    function getProperties($feature): string
    {
        return json_encode($this->viessmannFeatureProxy->getEntity($feature)->getProperties());
    }

`
Cordialement,
Philippe

**Comment by thetrueavatar** [comment]
Bonjour,
Pourrais-je vous demander de faire un simple pull request si vous l'avez
déjà implémenté ?
Bien à vous,

Le jeu. 18 févr. 2021 à 23:24, PhilippeJ-code <notifications@github.com> a
écrit :

**Comment by stanthewizzard** [comment]
Ton plugin est juste fantastique. Merci

**Comment by thetrueavatar** [comment]
solutionnée par PR
