### ISSUE TITLE
Is it possible to read the values of the energy balance?

### ISSUE THREAD

**Issue by tinom86** [thetrueavatar/Viessmann-Api#56]
Hi all,

is there a possibility to read the values of the energy balance via Viessmann-API (heating and water)? It is visible per calendar week in the menu.

![image](https://user-images.githubusercontent.com/79569479/110328243-63b1c880-801b-11eb-8b8f-33382f56f976.png)

In the Viessmann menu:
Service ->Diagnosis -> Energy Balance

BR
Tino

**Comment by Jumper78** [comment]
Hello @tinom86,

up to version 1.3.0, it was possible to read out the complete content of the API with the command json_decode($viessmannApi->getFeatures(), true);
You ended up with a huge json list you could search. To be honest, I have never seen those values in this complete list. It would surprise me if you can get them via the API.

One more remark:
After reading your question, I did read out the values for CW9 from my Viessmann heating system and got 325.4 kWh for heating and 34.3 kWh for hot water. That would be 359.7 kWh in total. But: this cannot be the correct value! My (smart-) meter tells me a total power consumption of 154 kWh for CW9. This value is the official one and it even includes also my ventilation system. My Viessmann system must have consumed about 140 kWh in CW9 and not 360 kWh. At least in my case, the values given by the Viessmann system are not trustworthy at all.

Cheers, Jump3r

**Comment by tinom86** [comment]
> Hello @tinom86,
> 
> up to version 1.3.0, it was possible to read out the complete content of the API with the command json_decode($viessmannApi->getFeatures(), true);
> You ended up with a huge json list you could search. To be honest, I have never seen those values in this complete list. It would surprise me if you can get them via the API.
> 
> One more remark:
> After reading your question, I did read out the values for CW9 from my Viessmann heating system and got 325.4 kWh for heating and 34.3 kWh for hot water. That would be 359.7 kWh in total. But: this cannot be the correct value! My (smart-) meter tells me a total power consumption of 154 kWh for CW9. This value is the official one and it even includes also my ventilation system. My Viessmann system must have consumed about 140 kWh in CW9 and not 360 kWh. At least in my case, the values given by the Viessmann system are not trustworthy at all.
> 
> Cheers, Jump3r

Hi,

damn... thought I get the information :(

Your values might be correct. The balance does not show electrical energy but heating energy. In CW9 your heater made 360 kWh heating energy out of 140 kWh electrical energy. That's what I understand?!?

Best
Tino

**Comment by Jumper78** [comment]
Now you caught my interest: the factor of 2.5 I saw between the values would then be the "Coefficient Of Performance". That would be a reasonable number, actually. Now I also would love to read out that value.

Nevertheless, I checked the total list of features (1.3 MB of json data) but did not find the value "325" anywhere else then in the heating.controller.serial. So, at least last weeks value seems not be in the data.

**Comment by soeffi** [comment]
Can you use the getHeatingPowerConsumption() for that purpose? Seems to work for me, but I haven't check against an external power meter to compare accuracy of the data.

In fact I do have an issue here, there is an example script "GetHeatingPowerConsumptionTotal.php" which uses a function getHeatingPowerConsumptionTotal(), that doesn't seem to exist - can anyone comment on that?

**Comment by Jumper78** [comment]
Concerning your first question: getHeatingPowerConsumption() does not work for my Viessmann heating system. The constant HEATING_POWER_CONSUMPTION in the class ViessmannFeature refers to "heating.power.consumption" which does not exist for my device. So, I can read a value on the screen of the device itself, but I cannot read the value via the API.

**Comment by thetrueavatar** [comment]
NA since we are using the new IOT Api
