### ISSUE TITLE
API officiel Viessmann

### ISSUE THREAD

**Issue by EricChanussot** [thetrueavatar/Viessmann-Api#58]
Bonjour Claude,
J’ai mon accès au portail des développeurs Viessmann et ai commencé à jouer avec l’API.
Des features manques, comme :

```
heating.burner.modulation
heating.burner.automatic
heating.burner.statistics (hours) and (starts)

heating.circuits.N.heating.curve (shift) and (slope)

heating.gas.consumption.dhw (total), (year), (month), (week) and (day)
heating.gas.consumption.heating (total), (year), (month), (week) and (day)
heating.power.consumption (total), (year), (month), (week) and (day)
```

Étant le dev de l’API cliente qui fait référence et faisant partie des testeurs, tu as peut-être déjà échangé avec viessmann sur le sujet ? 
Si ce n’est pas le cas, je suppose que plus on sera nombreux à demander l’implémentation de ces features a l’API, plus on aura de chance que ça aboutisse.
J’ai pour ma part fait une requête a developer@viessmann.com.
Merci pour ton retour.
Bien cordialement

**Comment by thetrueavatar** [comment]
Bonjour,
Pour ma part, j'ai rempli le questionnaire d'enquête.
Ils ont mis une section dédiée aux informations souhaitées. J'ai rajouté dans les choses qui me semblaient indispensable dibt toutes les écritures et les métriques comme tu l'as indiqué. Ils ont mis une section dédiée aux informations souhaitées.
J'ai aussi ajouté ma déception/surprise de ne pas avoir de definition openapi du service REST ce qui permettrait d'auto-généré un client comme le mien dans n'importe quel langage et sans développement spécifique.
Idem pour le support d'openid-connect qui est le standard authentification+autorisation. Seul l'Oauth pour la partie autorisation est supportée.
On verra ce que ça donnera.
Pour ma part, je suis assez déçu de ce qui est proposé. Ils n'ont fait qu'enlever la partie siren-json du modèle au final...
