### ISSUE TITLE
Raspi: Code is not executed

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#6]
Hi,
I installed php on my openhab2 (Raspi) Server and tried to run the php scripts.
php Shows following Version:

> PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright © 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright © 1998-2017 Zend Technologies
with Zend OPcache v7.0.30-0+deb9u1, Copyright © 1999-2017, by Zend Technologies

I receive following error message:

> php GetOutsideTemperature.php
PHP Notice: Use of undefined constant CURLOPT_URL - assumed ‘CURLOPT_URL’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 81
PHP Notice: Use of undefined constant CURLOPT_HTTPHEADER - assumed ‘CURLOPT_HTTPHEADER’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 82
PHP Notice: Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed ‘CURLOPT_SSL_VERIFYPEER’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 83
PHP Notice: Use of undefined constant CURLOPT_RETURNTRANSFER - assumed ‘CURLOPT_RETURNTRANSFER’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 84
PHP Notice: Use of undefined constant CURLOPT_USERPWD - assumed ‘CURLOPT_USERPWD’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 85
PHP Notice: Use of undefined constant CURLOPT_HTTPAUTH - assumed ‘CURLOPT_HTTPAUTH’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 86
PHP Notice: Use of undefined constant CURLAUTH_BASIC - assumed ‘CURLAUTH_BASIC’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 86
PHP Notice: Use of undefined constant CURLOPT_POST - assumed ‘CURLOPT_POST’ in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 87
PHP Fatal error: Uncaught Error: Call to undefined function Viessmann\Oauth\curl_init() in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php:89
Stack trace:
#0 phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php(56): Viessmann\Oauth\ViessmannOauthClientImpl->getCode()
#1 phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(43): Viessmann\Oauth\ViessmannOauthClientImpl->__construct(Array)
#2 /tmp/viessmann/bootstrap.php(13): Viessmann\API\ViessmannAPI->__construct(Array)
#3 /tmp/viessmann/GetOutsideTemperature.php(2): include(’/tmp/viessmann/…’)
#4 {main}
thrown in phar:///tmp/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php on line 89

A test with a fresh Raspbian Setup worked for mentioned method without problems, the corrrect temperature was received.
Any suggestion - what is going wrong?
Thanks Georg

**Comment by thetrueavatar** [comment]
Oops sorry, gmail did the translation in french so here is the answer in english:
php-curl is missing on your installation. You juste have to do the install through command line with this commande:
sudo apt-get install php-curl
It will asked you the current user's password.
I have updated documentation to add this explanation.
Best Regards,

**Comment by thetrueavatar** [comment]
Oops sorry, gmail did the translation in french so here is the answer in english:
php-curl is missing on your installation. You juste have to do the install through command line with this commande:
sudo apt-get install php-curl
It will asked you the current user's password.
Best Regards,

**Comment by JungeG** [comment]
Merci,
did understand your French Reply - but my French is not good enough to reply :-(
Did the Installation of php-curl - new error:

>  php GetOuts                     ideTemperature.php
PHP Warning:  include(phar:///etc/openhab2/transfer/viessmann/Viessmann-Api-0.4-                     SNAPSHOT.phar/index.php): failed to open stream: phar error: invalid url or non-                     existent phar "phar:///etc/openhab2/transfer/viessmann/Viessmann-Api-0.4-SNAPSHO                     T.phar/index.php" in /etc/openhab2/transfer/viessmann/bootstrap.php on line 6
PHP Warning:  include(): Failed opening 'phar:///etc/openhab2/transfer/viessmann                     /Viessmann-Api-0.4-SNAPSHOT.phar/index.php' for inclusion (include_path='.:/usr/                     share/php') in /etc/openhab2/transfer/viessmann/bootstrap.php on line 6
PHP Fatal error:  Uncaught Error: Class 'Viessmann\API\ViessmannAPI' not found i                     n /etc/openhab2/transfer/viessmann/bootstrap.php:18
Stack trace:
#0 /etc/openhab2/transfer/viessmann/GetOutsideTemperature.php(2): include()
#1 {main}
  thrown in /etc/openhab2/transfer/viessmann/bootstrap.php on line 18

Cordialement
Georg

**Comment by thetrueavatar** [comment]
You don't need to reply me in french. English is fine. I thought you were french because gmail did translate the email automaticaly in french..
For you problem, the file /etc/openhab2/transfer/viessmann/bootstrap.php tries to include the 
/etc/openhab2/transfer/viessmann /Viessmann-Api-0.4-SNAPSHOT.phar but doesn't seems to find it. Could you check that this file does exists ?

**Comment by JungeG** [comment]
oh sh...!
I deleted it, but forgot to copy it back.
Thanks it is working now for OutsideTemperature and BoilerTemperature - will test the remaining examples during next week.
Je te souhaite un bon week-end
Georg

**Comment by JungeG** [comment]
Hi - I am testing again.
First of all I had to reset my password on ViCare. The App Vitotrol Plus I cannot login any longer. The app is disconnected any how.
I changed the credentials.properties file to new password - now I get an error _Error during authentication process. Please review your username/password_
Any idea what is going wrong?
Thanks for a quick reply
Georg

**Comment by thetrueavatar** [comment]
To get more info, please add the bold line in the bootstrap.php file:
try {
$viessmannApi = new ViessmannAPI($params);
} catch (ViessmannApiException $e) {
    echo $e->getMessage();
    **echo "Trace:" . $e->getTraceAsString() . "\n";**
    exit();
}

**Comment by JungeG** [comment]
Trace after inserting:

> Error during authentication process. Please review your username/passwordTrace:#0 phar:///home/openhabian/Downloads/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php(56): Viessmann\Oauth\ViessmannOauthClientImpl->getCode()
#1 phar:///home/openhabian/Downloads/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(43): Viessmann\Oauth\ViessmannOauthClientImpl->__construct(Array)
#2 /home/openhabian/Downloads/bootstrap.php(18): Viessmann\API\ViessmannAPI->__construct(Array)
#3 /home/openhabian/Downloads/GetOutsideTemperature.php(2): include('/home/openhabia...')
#4 {main}

Hope this is the information you are looking for
Georg

**Comment by JungeG** [comment]
This version works:
675696 Nov 22 10:58 Viessmann-Api-0.4-SNAPSHOT.phar
This seems to be the version from beginning of November.

This version shows the error:
675759 Nov 22 10:50 Viessmann-Api-0.4-SNAPSHOT.phar
This is the actual version downloaded yesterday.

**Comment by thetrueavatar** [comment]
I didn't commit anything in the phar since 11 november. I have added the response of the viessmann server to understand the problem:
so now please take the latest version of the phar and update bootstrap.php:
try {
$viessmannApi = new ViessmannAPI($params);
} catch (ViessmannApiException $e) {
    echo $e->getPrevious()->getMessage();
    exit();
}

**Comment by JungeG** [comment]
Hi,
the working version ist before 11.11. probably 08.11
now as follows:

> PHP Fatal error:  Uncaught Error: Call to a member function getMessage() on null in /home/openhabian/Downloads/bootstrap.php:20
Stack trace:
#0 /home/openhabian/Downloads/GetOutsideTemperature.php(2): include()
#1 {main}
  thrown in /home/openhabian/Downloads/bootstrap.php on line 20

line 20 ist the line with getPrevious().
does this help?
Georg

**Comment by thetrueavatar** [comment]
Well it does tell you that echo $e->getPrevious() is null which according to me is not possible if you did update your phar with latest version. Could you check that you have correctly updated the phar ?

**Comment by JungeG** [comment]
I am bit confused - just downloaded the actual Viessmann...phar which has a different size than the one of this morning.

> php GetOutsideTemperature.php
response didn't contains code to get token probably due to an error in authentication process. Response :     

 



 


  
<!DOCTYPE html>
<html>
	<head>
		<title>Viessmann Login</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="icon" href="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/images/favicon.png" type="image/png">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900"/>
		<link rel="stylesheet" href="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/css/material.min.css"/>
    	<link rel="stylesheet" href="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/css/getmdl-select.min.css"/>
    	<link rel="stylesheet" href="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/css/customerRegistration.css"/>
        <script src="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/js/material.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
	<div class="b2b-main-background"> 	    <div class="font-size-20px b2b-regestration-headline">             <div class="mdl-grid mdl-grid--no-spacing">                 <div class="b2b-regestration-headline-item" style="margin-left:24px">Login</div>
            </div>         </div> 
        <div class="b2b-main-container">             <div class="b2b-sub-container">                 <div class="mdl-grid mdl-grid--no-spacing">                     <div class="mdl-layout-spacer"></div>
                    <img src="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/images/viessmann-logo.png" alt="viessmann-logo" class="b2b-vi-image"/>
                    <div class="mdl-layout-spacer"></div>
                </div>                 <form class="b2b-form-space" id="AuthUidPwDialog" name="AuthUidPwDialog" method="POST" target="_self" action="https://iam.viessmann.com/idp/v1/authorize?client_id=79742319e39245de5f91d15ff4cac2a8&amp;scope=openid&amp;redirect_uri=vicare://oauth-callback/everest&amp;response_type=code" autocomplete="off" accept-charset="UTF-8">  
<div class="mdl-grid mdl-grid--no-spacing">
    <div class="mdl-layout-spacer"></div>
        <div class="error-color normal-text font-size-26px opacity-87 b2b-form-space b2b-line-height"><p>Login failed; please check the details you have entered.</p></div>
    <div class="mdl-layout-spacer"></div>
</div>


 
 







<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">   <input class="mdl-textfield__input" autocorrect="off" autocapitalize="off" autocomplete="off" spellcheck="false" 
      type="text" id="isiwebuserid" name="isiwebuserid" size="20" maxlength="255" tabindex="2">
  <label class="mdl-textfield__label" for="isiwebuserid">User name</label>
</div> 

	
 
 







<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">   <input type="password" name="hidden-password" value="00" tabindex="-1" style="display:none" autocomplete="off">
  <input class="mdl-textfield__input" autocorrect="off" autocapitalize="off" autocomplete="off" spellcheck="false" 
      type="password" id="isiwebpasswd" name="isiwebpasswd" size="20" maxlength="255" tabindex="3">
  <label class="mdl-textfield__label" for="isiwebpasswd">Password</label>
</div> 

	
 
 






<div class="mdl-grid mdl-grid--no-spacing" style="padding-top:16px">   <div class="mdl-cell" style="width:auto">   <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox">     <input type="checkbox" name="stayloggedin" value="Stay logged on" tabindex="4" class="mdl-checkbox__input" id="checkbox" style="margin-left:0">
    <span class="mdl-checkbox__label">Stay logged on</span>
  </label>   </div> 

	
 



 



                                                <div class="mdl-layout-spacer"></div>
        <div class="mdl-cell" style="width:auto;margin-top:5px">           <a class="forgot-username-password" id="link_pwlost" title="Forgotten password" href="/selfservice/passwordlost">Forgotten password</a>
        </div>         </div>                 










<div class="mdl-grid mdl-grid--no-spacing" style="padding-top:60px">   <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell" style="width:auto">     <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored login-button" type="submit" name="submit" value="LOGIN" id="loginButton">LOGIN</button>
  </div> </div> 

 
                </form>                 <script type="text/javascript">document.forms['AuthUidPwDialog'].elements[0].focus()</script>
            </div>         </div>         <div class="mdl-layout-spacer"></div>     </div>  
						<script src="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/js/jquery-1.11.2.min.js"></script>
		<script src="/login/resources/nevislogrend/applications/IDM_OIDC_IDP_V1/webdata/js/nevislogrend.js"></script>
	</body> </html> 



 Trace:#0 phar:///home/openhabian/Downloads/Viessmann-Api-0.4-SNAPSHOT.phar/src/Oauth/ViessmannOauthClientImpl.php(56): Viessmann\Oauth\ViessmannOauthClientImpl->getCode()
#1 phar:///home/openhabian/Downloads/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(43): Viessmann\Oauth\ViessmannOauthClientImpl->__construct(Array)
#2 /home/openhabian/Downloads/bootstrap.php(18): Viessmann\API\ViessmannAPI->__construct(Array)
#3 /home/openhabian/Downloads/GetOutsideTemperature.php(2): include('/home/openhabia...')
#4 {main}

This is the error message I receive.
Georg

**Comment by thetrueavatar** [comment]
Well Viessmann server clearly complains about your given credentials... "Login failed; please check the details you have entered."
I receive the same error when I intentionaly enter a wrong password.
I have checked and didn't change for at least one month and maybe even more.
My guess is that's a problem with the credentials provided. You could have more information if in the bootstrap.php:
`try {
$viessmannApi = new ViessmannAPI($params);
} catch (ViessmannApiException $e) {
    print_r($e->getTrace());
    exit();
}`
This will display an array of 4 item. The second and third should show you the state of the variable user and pwd. Don't put them here but you could check if it's you're credentials... If you're using the credentials.properties file ensure that you don't have a third empty line.

**Comment by JungeG** [comment]
Checked credentials file - not working.
Copied a credentials.properties from a working copy - it is working now.
Don't understand content (user and password) and size of both files was identical.
Thanks
Georg
