### ISSUE TITLE
Issues with new Viessmann API authentication

### ISSUE THREAD

**Issue by soeffi** [thetrueavatar/Viessmann-Api#61]
Salut thetrueavatar,

my connection to Viessmann servers stopped working (expectedly) today, and I tried to setup the new 2.0.0 snapshot - unfortunately I can't get it to work, hope you can help.

I have successfully created a client Id in Viessmann's developer portal and setup the new credentials and bootstrap file accordingly. (Note: Manually calling the authorize endpoint in a browser brings up the login form, after login I receive an authorization code encoded in the URL)

However, with your scripts, when trying to read any value, I end up with `Error during authentication process. Please review your username/password`, obviously because Viessmann wants the authorization process to be initiated from a browser, as is it includes some kind of captcha.

Could you give me a hint how to work around that or what I might be missing?

Merci beaucoup et bonne soirée!
Stefan

**Comment by ocramleznem** [comment]
Hi @soeffi 
I just upgraded my client from 1.4.0 to 2.0.0. I created a client in the developer portal (URI doesnt matter, as far as i tried. Just let it be the default. Disable the Google reCAPTCHA check).
After that use the `bootstrap.php` and the `credentials.properties` from the 2.0.0 release for a first test. In `credentials.properties` you should enter your user, password and the newly created client id. Just like that:
```
user=mail@mail.xz
pwd=yourPassword
clientId=yourClientId
installationId=
gatewayId=
deviceId=0
circuitId=0
```
Then try to execute the `bootstrap.php` and see what happens.

**Comment by soeffi** [comment]
Thanks a lot, I must have been blind - although I found out, that the Captcha check is the problem, I just didn't realize that there is a simple switch to turn it off...

My bad, thanks a lot for the hint, now it's working fine. Some features seem to have changed (notably the `burner.*` features became `burners.0.*`, but that's another issue. Will close this one...

@thetrueavatar : Although it might be obvious to others, maybe you'd like to include the hint to turn of "ReCaptcha" in the developer portal in your Readme, just for people like me :-) )

**Comment by thetrueavatar** [comment]
I guess I did disabel it a couple month ago because I wasn't aware of this.
I will add it into the readme as suggested.
Regards,
