### ISSUE TITLE
for information, futures not working in new api for my OPT1 (Vitoconnect 100) but before working fine

### ISSUE THREAD

**Issue by dr-boss** [thetrueavatar/Viessmann-Api#64]
1. heating.service.timeBased  - GetServiceInterval(), GetLassServiceDate(), GetActiveMonthSinceService() - No such Feature
2. heating.circuits.0.operating.programs.holiday - getScheduledHolidayProgram(), unscheduleHolidayProgram(), scheduleHolidayProgram("2019-08-30", "2019-08-31") - No such Feature

**Comment by rogrun** [comment]
I am very busy at the moment. Some fuetures are no longer available in the new API. I'll try to find the possible bug in the next few days.

**Comment by dr-boss** [comment]
I understand that these functions are less necessary than the basic ones. I wrote for information. If you add them one day, it will simply be easier to integrate with Fibaro, for example
Your job is great anyway

**Comment by rogrun** [comment]
1. heating.service.timeBased is currently not available. Perhaps @thetrueavatar can look in the new API documentation to see if the BASE URL for service information has changed.
2. For HolidayProgram, please download the .phar from yesterday. It should fix it.
Let us know if it works, or not

**Comment by thetrueavatar** [comment]
Since ViCare is using the IOT Api, if an information is available in ViCare it should be available then with the IOT API.
Some feature are no more under the same root url path. For instance installationId and  gatewayId are found under the equipment/gateways path. I guess that the timeBased feature is no more available with the usual path. Still have to find the right place.

**Comment by thetrueavatar** [comment]
I should take some time to check how the feature are now reorgarnized and clean a bit the way I'm working. For the cache, I'm get the data from the https://api.viessmann.com/iot/v1/equipment/installations/{installationId}/gateways/{gatewaySerial}/devices/{deviceId}/features/
while they are other available:
https://api.viessmann.com/iot/v1/equipment/installations/{installationId}/gateways/{gatewaySerial}/features/
https://api.viessmann.com/iot/v1/equipment/installations/{installationId}/features/

Documentation is not quiete clear atm.

Plese note that viessmann has added some features accodring to their changelog https://developer.viessmann.com/en/doc/changelog


> New data points available - Diagnostic information
> In order to better transition from the old API usage and into the Developer Portal for our users and developers, the following additional features can now be used via the API:
> 
> heating.circuits.N.heating.curve - Displays values that go into the heating curve and provides commands to change them: slope and shift.
> 
> heating.burner.N.modulation - Shows information about the current burner modulation
> 
> heating.compressor.N.statistics - Shows the statistics of compressor N: hours and start times
> 
> heating.burner.N.statistics - Shows the statistics of the burners: Hours and times started
> 
> heating.solar.power.production - Shows the statistics of the solar power production: daily, weekly, monthly, yearly
> 
> heating.gas.consumption.dhw - Shows the statistics of gas consumption for heating domestic hot water
> 
> heating.gas.consumption.heating - Shows statistics of gas consumption for heating
> 
> heating.power.consumption - Power usage: daily, weekly, monthly, yearly
> 
> The list of all available data points can be found in the "IoT - Data points" section: https://developer.viessmann.com/de/doc/iot/data-points.
> 
> Note: The functions of the basic (free) variant of the API are a temporary offer and the scope may change over time.
> 
> Developer forum now available
> We are happy to announce that a dedicated Viessmann Community area for developers is now available: https://www.viessmann-community.com/t5/Developer/ct-p/Developer
> 
> In this area, you will find new announcements and information around our API. You will also be able to post your questions and exchange with other developers around the API.
> 
> We look forward to great exchanges and co-creation among all developers!

**Comment by fredchal** [comment]
I use the hot water setpoint in my setup. Since yesterday, the feature getDhwTemperature() (=heating.dhw.temperature) is no longer available. After comparing the complete rawjsondata, I noticed that the feature with the required value is heating.dhw.temperature.main. But this feature is not available in the script or am I wrong?

**Comment by thetrueavatar** [comment]
> I use the hot water setpoint in my setup. Since yesterday, the feature getDhwTemperature() (=heating.dhw.temperature) is no longer available. After comparing the complete rawjsondata, I noticed that the feature with the required value is heating.dhw.temperature.main. But this feature is not available in the script or am I wrong?

Hello, could you please create a specific issue for this one. This will help me to manage issue. I'm already looking at it.
EDIT: I have created the issue myself https://github.com/thetrueavatar/Viessmann-Api/issues/67

**Comment by dr-boss** [comment]
> 
> 
>     1. heating.service.timeBased is currently not available. Perhaps @thetrueavatar can look in the new API documentation to see if the BASE URL for service information has changed.
> 
>     2. For HolidayProgram, please download the .phar from yesterday. It should fix it.
>        Let us know if it works, or not

Not work yet :(
$viessmannApi->getScheduledHolidayProgram();
and the resault:
Message: Unable to get data for feature heating.circuits.0.operating.programs.holiday
 Reason: No such Feature
Code: 0

**Comment by rogrun** [comment]
In the API documentation are two features provided. But I don't know if it is the same. Please try this:

```
<?php
include __DIR__ . '/bootstrap.php';

use Viessmann\API\ViessmannFeature;

echo "heating.operating.programs.holiday: ";
print_r ($viessmannApi->getRawJsonData("heating.operating.programs.holiday"));
echo "\n";
```

If it works on your installation, we have to do some tests and then we can fix it.

**Comment by dr-boss** [comment]
> 
> 
>     1. heating.service.timeBased is currently not available. Perhaps @thetrueavatar can look in the new API documentation to see if the BASE URL for service information has changed.
> 
>     2. For HolidayProgram, please download the .phar from yesterday. It should fix it.
>        Let us know if it works, or not

Same error like before. Not working

**Comment by dr-boss** [comment]
> 
> 
> In the API documentation are two features provided. But I don't know if it is the same. Please try this:
> 
> ```
> <?php
> include __DIR__ . '/bootstrap.php';
> 
> use Viessmann\API\ViessmannFeature;
> 
> echo "heating.operating.programs.holiday: ";
> print_r ($viessmannApi->getRawJsonData("heating.operating.programs.holiday"));
> echo "\n";
> ```
> 
> If it works on your installation, we have to do some tests and then we can fix it.

Ok,, its work via "heating.operating.programs.holiday"

**Comment by dr-boss** [comment]
Thx for this function, I start read new API doc...

**Comment by thetrueavatar** [comment]
I have updated the code so that $viessmannApi->getScheduledHolidayProgram() is using the right feature
