### ISSUE TITLE
getRawJsonData / setRawJsonData don't work with new V api?

### ISSUE THREAD

**Issue by dr-boss** [thetrueavatar/Viessmann-Api#65]
When I use  getRawJsonData the error is:
PHP Notice:  Undefined variable: allfeatures in phar:///home/pi/Viessmann-Api/example.org/Viessmann-Api-2.1.0-SNAPSHOT.phar/src/API/proxy/impl/ViessmannFeatureLocalProxy.php on line 46

**Comment by thetrueavatar** [comment]
This afternoon I have merged a pr. Did you update your version today ?

**Comment by dr-boss** [comment]
no yesterday ;-), I will check with new one in the moment

**Comment by dr-boss** [comment]
I will check tomorrow, because ... API calls rate limit has been exceeded. ;-)

**Comment by thetrueavatar** [comment]
I have fixed the getRawJsonData. It was indeed broken.
Could you check please ?

**Comment by rogrun** [comment]
I've checked. It is working for me.
