### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by Wojcieech** [thetrueavatar/Viessmann-Api#7]
Do you have plans integrating this in HA?

**Comment by thetrueavatar** [comment]
No. my plan is to provide an API that Can be use by people to integrate in
their preferred platform but I won't do the work myself because I have no
knowledge of those platform.
I want to keep as much as possible the portability of this and avoid  to be
tied to a specific platform.
Best regards

**Comment by Wojcieech** [comment]
Thank you for your answer.
