### ISSUE TITLE
Consommations électriques et gaz ne remontent plus

### ISSUE THREAD

**Issue by TricloFL78** [thetrueavatar/Viessmann-Api#70]
Les consommations gaz et électriques ne remontent plus !
Les dernières valeurs remontées datent du 09/08/2021 (date à laquelle j'ai paramétré sur Vicare que j'étais en vacances pour ne plus consommer). Au retour des vacances, j'ai réactivé. Ca marche sur ViCare mais pas dans l'application alors que je n'ai rien changé. Est-ce que quelqu'un a rencontré la même situation ?

**Comment by TricloFL78** [comment]
Sorry, I've written in French.
Since I took my vacation, I don't have anymore gas and elctricity consumption. Do anybody have the same problem ?
What are solutions ?

**Comment by TricloFL78** [comment]
It seems that codification of electricity consumption has changed. For gas, it's ok.
I got the following message for daily consumption :"Message: Unable to get data for feature heating.power.consumption Reason: No such Feature".

**Comment by rogrun** [comment]
Viessmann changed many features since august. I'm working on fixing it. I'll need some time for this.

**Comment by thetrueavatar** [comment]
> Viessmann changed many features since august. I'm working on fixing it. I'll need some time for this

Thank you for taking the time to fix this since I don't have the time to do this. 
An api is supposed to have some stability but viessman doesn't seem to follow that basic rule

**Comment by thetrueavatar** [comment]
I have merged the change from the pr of rogrun. @TricloFL78  Could you test ?

**Comment by TricloFL78** [comment]
Thanks @thetrueavatar.
I will test as soon as I can and I will give the answer if it's working or not.

**Comment by TricloFL78** [comment]
Hi @thetrueavatar,

I've done the test. It doesn't work and I have the following message "Résultat de la commande : Message: Unable to get data for feature heating.burners.0.heating.burners Reason: No such Feature Code: 0" for day, week, month and year.
Tests are done in my Jeedom docker.

**Comment by thetrueavatar** [comment]
Did you upgrade your bootstrap.php to use the new phar ? I don't quite understand why the method getHeatingPowerConsumption would try to use heating.burners.0.heating.burners
Wich method are you using ?

**Comment by TricloFL78** [comment]
I used the bootstrap.php and phar 2.1.1 from "develop" and "example".

**Comment by rogrun** [comment]
I'm in the hospital right now.  a routine intervention.  I'll check it out as soon as possible when I'm home. Normally getHeatingPowerConsumption should call the correct feature.

**Comment by thetrueavatar** [comment]
> I used the bootstrap.php and phar 2.1.1 from "develop" and "example".

Can you provide me the exact code you're using to get that error ? Just to reproduce the problem.
@rogrun take your time to have a rest. This is far more important than providing a support for this.

**Comment by TricloFL78** [comment]
En pièce jointe le zip avec les 2 fichiers utilisés.
[Env.zip](https://github.com/thetrueavatar/Viessmann-Api/files/7211194/Env.zip)

**Comment by thetrueavatar** [comment]
ok mais c'est quelle fonction ?
exemple: 
`print_r( $viessmannApi->getHeatingPowerConsumption('day') );`

**Comment by TricloFL78** [comment]
Voilà l'extrait de mon PHP :
//Consommation électrique 
$cmd = cmd::byId(CMD_CONSO_EL_DAY);
$virtual->checkAndUpdateCmd($cmd, $viessmannApi->getHeatingPowerConsumption('day')[0]);
$cmd = cmd::byId(CMD_CONSO_EL_WEEK);
$virtual->checkAndUpdateCmd($cmd, $viessmannApi->getHeatingPowerConsumption('week')[0]);
$cmd = cmd::byId(CMD_CONSO_EL_MONTH);
$virtual->checkAndUpdateCmd($cmd, $viessmannApi->getHeatingPowerConsumption('month')[0]);
$cmd = cmd::byId(CMD_CONSO_EL_YEAR);
$virtual->checkAndUpdateCmd($cmd, $viessmannApi->getHeatingPowerConsumption('year')[0]);

**Comment by thetrueavatar** [comment]
Chez moi ce code fonctionne parfaitement tout en ayant pris ton fichier env.zip. Je pense qu'il y a quelque chose de pas net dans ton installation jeedom.

**Comment by TricloFL78** [comment]
Noté.
J'ai 2 Jeedom. Je viens de tester sur le 2ième et j'obtiens le même résultat. Toutes les autres "features" de tes développements fonctionnent parfaitement. Pourquoi pas pour l'électricité si ça marche chez toi ? Mystère !
J'ai installé le plugin Jeedom de PhilippeJ et j'ai bien les valeurs des consommations électriques qui remontent. Là est l'essentiel.

Merci pour ta super implication.

**Comment by thetrueavatar** [comment]
Ce qui m'étonne c'est que la feature not found mentionnée n'existe plus
dans le code donc ça ne peut venir que d'une vieille version.
Bien à toi


Le jeu. 23 sept. 2021 à 19:41, TricloFL78 ***@***.***> a
écrit :

**Comment by TricloFL78** [comment]
Je viens de charger la nouvelle version. 
Les informations remontent.
Je ferme ce fil.
