### ISSUE TITLE
Some features broken (?)

### ISSUE THREAD

**Issue by soeffi** [thetrueavatar/Viessmann-Api#73]
Hi all,

since today morning I'm getting some errors in my scripts, related to burner information. I see:

Unable to get data for feature heating.burner from isHeatingBurnerActive()
Unable to get data for feature heating.burners.0.heating.burners from getHeatingBurnerStatistics()

Yet another API change? I'm using the latest (2.1.1) snapshot. Anyone else with the same issue?

Thanks!

**Comment by rogrun** [comment]
Hi soeffi,

same issue here. I see that Viessmann does not provide the data for the feature e.g. for burners. So there is no issue on the part of this API. 

I do not know if it will only be for a short time.

In the API Documentation from Viessmann are no further information.

**Comment by thetrueavatar** [comment]
same for me. One way to fix that would be to find the right feature name by sniffing network from viCare to viessmann's server. I only succeed this by using android sdk emulator+ mitmproxy which takes me a bit of effort. Didn't succeed with vpn traffic sniffer such ash Packet Capture.

**Comment by thetrueavatar** [comment]
there is a bug in the feature construction for statistics. should be heating.burners.0.statistics not heating.burners.0.heating.burners. W

**Comment by thetrueavatar** [comment]
I have fixed the problem with statistics. Will check for burner active.

**Comment by thetrueavatar** [comment]
BTW One easy way to get all the feature available is to disable caching in the boostrap-dev.php
`try {
    $viessmannApi = new ViessmannAPI($params,false);
} catch (ViessmannApiException $e) {
    $errorHandler($e);
    exit();
}`

 and use:


```
<?php
include __DIR__.'/bootstrap-dev.php';
echo $viessmannApi->getRawJsonData(""):
```

**Comment by thetrueavatar** [comment]
burner is now under feature heating.burners.0 did a fix for this.
A bit tired of all those change. IMHO, they are exposing a bit too much their own implementation mechanism instead of just providing high level interface... We could just read all the raw data from the root path but I need some parsing to display things...

**Comment by thetrueavatar** [comment]
For my part issue is closed. Feel free to reopen if not

**Comment by soeffi** [comment]
> For my part issue is closed. Feel free to reopen if not

Same here. Works with the latest 2.1.1 snapshot. Thanks a lot for the quick response!
