### ISSUE TITLE
GetAllInformation: Warning

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#8]
I am currently testing all programs:
GetAllInformation generates following warning:

> PHP Warning:  fopen(http://192.168.0.2/core/api/jeeApi.php?plugin=virtual&apikey=SKqLrR6l8T7CB4REvAEj7DHKfrJHa0PM&type=virtual&id=1022&value=3): failed to open stream: Connection timed out in /etc/openhab2/transfer/viessmann/GetAllInformation.php on line 14
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/transfer/viessmann/GetAllInformation.php on line 18

I have different IP-Adress range (http://192.168.XXX.Y/)range - should this be changed in Viessmann....phar file?

Thanks for some hints
Georg

**Comment by thetrueavatar** [comment]
Hum I did commit a file with some personnal data. I will update it and remove data bound to my own installation.

**Comment by JungeG** [comment]
I have now copied the new version:

> const JEEDOM_IP = "192.168.0.2";
const JEEDOM_API_KEY = "";

Which IP-address is used here?  The IP-address of the server on which the program is executed? 

If I use the actual IP-address I get following error message:

> ./GetAllInformation.php
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1022&value=4.5): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1024&value=61): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1027&value=1.2): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1028&value=23): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1018&value=EauChaude+Chauffage): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1019&value=Normal): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1021&value=1): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 29
PHP Notice:  Use of undefined constant JEEDOM_API - assumed 'JEEDOM_API' in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 38
PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25
PHP Warning:  fopen(http://JEEDOM_API/core/api/jeeApi.php?plugin=virtual&apikey={}&type=virtual&id=1023&value=55.2): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /etc/openhab2/scripts/viessmann/GetAllInformation.php on line 25

Thanks for advice

**Comment by thetrueavatar** [comment]
This script is an example to show how to get all information and push it to
the jeedom server. IP address and key are specific to jeedom. Since you're
using openhab this isn't useful for you.
Claude

**Comment by JungeG** [comment]
GetAllInformation.php is only relevant for jeedom users.
