### ISSUE TITLE
2nd Heating Circuit - Floor Heating

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#9]
Hi Claude,
I have 2 heating circuits - one for the "normal" radiators and one for a floor heating system.
Is there a change to include this 2nd heating circuit?
Thanks for a short reply.
Georg

**Comment by thetrueavatar** [comment]
I have added this functionnality a month ago.
You can specify the default circuit to use in the boostrap.php("circuitId"=>
"0") and also overwritte it by passing the circuitId as parameter of the
method call (ex: $viessmannApi->getActiveMode(3) )
Best Regards,
thetrueavatar

**Comment by JungeG** [comment]
Merci beaucoup.
Georg
